// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * endNumber?: number // End Number
}} Props

 */
import { routes } from "../chunks/chunk-NJY7DQ5Z.js"

// virtual:widget/stats
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/we9ikb0l6WOHkcp9qx31/vbL3KV4CoEDTkHGGTq2I/FrDAQD2_M.js
import { jsx as _jsx2 } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef as useRef2 } from "react"

// /:https://framerusercontent.com/modules/PiqKOL7ZE72lwOwkt3CZ/2Hc8OGbZKbYqGXw4ohVa/Counter1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import { useState, useEffect, useRef } from "react"
import { motion } from "unframer"
import { addPropertyControls, ControlType } from "unframer"
var CounterStyles = {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
}
function Counter(props) {
  const {
    start,
    end,
    speed,
    gapSize,
    prefixText,
    suffixText,
    prefixFont,
    suffixFont,
    prefixColor,
    suffixColor,
    loop,
    decimalSeparatorType,
    textSize,
    selectedFont,
    textColor,
    startOnViewport,
    restartOnViewport,
    incrementType,
  } = props
  const [count, setCount] = useState(start)
  const [isVisible, setIsVisible] = useState(false)
  const containerRef = useRef(null)
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      const entry = entries[0]
      setIsVisible(entry.isIntersecting)
    })
    if (containerRef.current) {
      observer.observe(containerRef.current)
    }
    return () => {
      if (containerRef.current) {
        observer.unobserve(containerRef.current)
      }
    }
  }, [])
  useEffect(() => {
    const updateCount = () => {
      const increment = incrementType === "integer" ? 1 : 0.1
      if (count < end) {
        setCount((prevCount) => parseFloat((prevCount + increment).toFixed(1)))
      } else if (loop) {
        setCount(start)
      }
    }
    if (isVisible || (!startOnViewport && start !== end)) {
      const intervalId = setInterval(updateCount, speed)
      return () => {
        clearInterval(intervalId)
      }
    } else if (startOnViewport && isVisible) {
      setCount(start)
    }
  }, [
    count,
    start,
    end,
    loop,
    isVisible,
    speed,
    startOnViewport,
    incrementType,
  ])
  useEffect(() => {
    if (restartOnViewport && isVisible) {
      setCount(start)
    }
  }, [isVisible, restartOnViewport, start])
  const formatNumber = (number) => {
    if (decimalSeparatorType === "comma") {
      return number.toLocaleString("en-US")
    } else if (decimalSeparatorType === "period") {
      return number.toLocaleString("en-US").replace(/,/g, ".")
    } else {
      return number.toFixed(incrementType === "integer" ? 0 : 1)
    }
  }
  return (
    <motion.div
      ref={containerRef}
      style={{
        ...CounterStyles.container,
        gap: `${gapSize}px`,
        flexDirection: "row",
        alignItems: "center",
        fontSize: `${textSize}px`,
        fontFamily: selectedFont.fontFamily,
        fontWeight: selectedFont.fontWeight,
        color: textColor,
      }}
    >
      <span
        style={{
          fontFamily: prefixFont.fontFamily,
          fontWeight: prefixFont.fontWeight,
          color: prefixColor,
        }}
      >
        {prefixText}
      </span>
      <span>{formatNumber(count)}</span>
      <span
        style={{
          fontFamily: suffixFont.fontFamily,
          fontWeight: suffixFont.fontWeight,
          color: suffixColor,
        }}
      >
        {suffixText}
      </span>
    </motion.div>
  )
}
Counter.defaultProps = {
  start: 0,
  end: 100,
  speed: 100,
  prefixText: "",
  suffixText: "",
  loop: false,
  decimalSeparatorType: "comma",
  textSize: 36,
  selectedFont: {
    fontFamily: "Manrope",
    fontWeight: 500,
    systemFont: true,
  },
  textColor: "#D3D3D3",
  startOnViewport: false,
  incrementType: "integer",
}
addPropertyControls(Counter, {
  startOnViewport: {
    type: ControlType.Boolean,
    title: "Viewport",
    defaultValue: false,
    enabledTitle: "On",
    disabledTitle: "Off",
  },
  restartOnViewport: {
    type: ControlType.Boolean,
    title: "Replay",
    defaultValue: false,
    enabledTitle: "Yes",
    disabledTitle: "No",
  },
  selectedFont: {
    title: "Font",
    type: ControlType.Font,
    defaultValue: {
      fontFamily: "Manrope",
      fontWeight: 500,
      systemFont: true,
    },
  },
  textSize: {
    title: "Font Size",
    type: ControlType.Number,
    min: 8,
    max: 240,
    step: 1,
  },
  textColor: {
    type: ControlType.Color,
    title: "Font Color",
  },
  start: {
    type: ControlType.Number,
    title: "Start Number",
    defaultValue: 0,
    displayStepper: true,
  },
  end: {
    type: ControlType.Number,
    title: "End Number",
    defaultValue: 10,
    displayStepper: true,
  },
  decimalSeparatorType: {
    type: ControlType.Enum,
    title: "Separator",
    defaultValue: "comma",
    options: ["comma", "period", "none"],
    optionTitles: ["Comma (1,000)", "Decimal (1.000)", "None"],
  },
  incrementType: {
    type: ControlType.Enum,
    title: "Increment Type",
    defaultValue: "integer",
    options: ["integer", "decimal"],
    optionTitles: ["Integer", "Decimal"],
  },
  prefixText: {
    type: ControlType.String,
    title: "Prefix",
    defaultValue: "",
  },
  prefixFont: {
    title: "Prefix Font",
    type: ControlType.Font,
    defaultValue: {
      fontFamily: "Manrope",
      fontWeight: 400,
      systemFont: true,
    },
  },
  prefixColor: {
    type: ControlType.Color,
    title: "Prefix Color",
  },
  suffixText: {
    type: ControlType.String,
    title: "Suffix",
    defaultValue: "",
  },
  suffixFont: {
    title: "Suffix Font",
    type: ControlType.Font,
    defaultValue: {
      fontFamily: "Manrope",
      fontWeight: 500,
      systemFont: true,
    },
  },
  suffixColor: {
    type: ControlType.Color,
    title: "Suffix Color",
  },
  gapSize: {
    type: ControlType.Number,
    title: "Gap Size",
    defaultValue: 4,
    min: 0,
    max: 100,
    step: 4,
  },
  speed: {
    type: ControlType.Number,
    title: "Speed (ms)",
    defaultValue: 100,
    min: 0,
    max: 2e3,
    step: 10,
  },
  loop: {
    type: ControlType.Boolean,
    title: "Loop Animation",
    defaultValue: false,
    enabledTitle: "On",
    disabledTitle: "Off",
  },
})

// /:https://framerusercontent.com/modules/we9ikb0l6WOHkcp9qx31/vbL3KV4CoEDTkHGGTq2I/FrDAQD2_M.js
var CounterFonts = getFonts(Counter)
var serializationHash = "framer-ITy2g"
var variantClassNames = {
  pvM7IoesC: "framer-v-uxng2j",
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion2.create(React.Fragment)
var getProps = ({ endNumber, height, id, width, ...props }) => {
  return {
    ...props,
    Ke261DEj7: endNumber ?? props.Ke261DEj7 ?? 10,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const { style, className, layoutId, variant, Ke261DEj7, ...restProps } =
    getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "pvM7IoesC",
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = []
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion2.div
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-uxng2j",
              className,
              classNames
            )}
            data-framer-name={"Default"}
            layoutDependency={layoutDependency}
            layoutId={"pvM7IoesC"}
            ref={refBinding}
            style={{
              ...style,
            }}
          >
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={"framer-1oig2z0-container"}
                isAuthoredByUser={true}
                layoutDependency={layoutDependency}
                layoutId={"sxOo6rVaS-container"}
                nodeId={"sxOo6rVaS"}
                rendersWithMotion={true}
                scopeId={"FrDAQD2_M"}
              >
                <Counter
                  decimalSeparatorType={"none"}
                  end={Ke261DEj7}
                  gapSize={4}
                  height={"100%"}
                  id={"sxOo6rVaS"}
                  incrementType={"integer"}
                  layoutId={"sxOo6rVaS"}
                  loop={false}
                  prefixColor={
                    "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))"
                  }
                  prefixFont={{
                    fontFamily: '"Outfit", "Outfit Placeholder", sans-serif',
                    fontStyle: "normal",
                    fontWeight: 700,
                  }}
                  prefixText={""}
                  restartOnViewport={true}
                  selectedFont={{
                    fontFamily: '"Manrope", "Manrope Placeholder", sans-serif',
                    fontStyle: "normal",
                    fontWeight: 500,
                  }}
                  speed={15}
                  start={0}
                  startOnViewport={true}
                  suffixColor={
                    "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))"
                  }
                  suffixFont={{
                    fontFamily: '"Outfit", "Outfit Placeholder", sans-serif',
                    fontStyle: "normal",
                    fontWeight: 700,
                  }}
                  suffixText={""}
                  textColor={
                    "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))"
                  }
                  textSize={26}
                  width={"100%"}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion2.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ITy2g.framer-1d5ecdy, .framer-ITy2g .framer-1d5ecdy { display: block; }",
  ".framer-ITy2g.framer-uxng2j { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-ITy2g .framer-1oig2z0-container { flex: none; height: auto; position: relative; width: auto; }",
]
var FramerFrDAQD2_M = withCSS(Component, css, "framer-ITy2g")
var stdin_default = FramerFrDAQD2_M
FramerFrDAQD2_M.displayName = "Widget / Stats"
FramerFrDAQD2_M.defaultProps = {
  height: 35.5,
  width: 35,
}
addPropertyControls2(FramerFrDAQD2_M, {
  Ke261DEj7: {
    defaultValue: 10,
    displayStepper: true,
    title: "End Number",
    type: ControlType2.Number,
  },
})
addFonts(
  FramerFrDAQD2_M,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Manrope",
          source: "fontshare",
          style: "normal",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BNWG6MUI4RTC6WEND2VPDH4MHMIVU3XZ/R5YXY5FMVG6PXU36GNEEA24MIPMEPGSM/CIM4KQCLZSMMLWPVH25IDDSTY4ENPHEY.woff2",
          weight: "500",
        },
        {
          family: "Outfit",
          source: "fontshare",
          style: "normal",
          url: "https://framerusercontent.com/third-party-assets/fontshare/wf/EUV6IZMPXOYBUY6KFIXKZWM47ESY5XYA/BLW2AGODUKQKRMYEVOEMMPY2ITRKBJIP/OKGWSU2PUNNFKQVFV2XFOSAHRXYREMR2.woff2",
          weight: "700",
        },
      ],
    },
    ...CounterFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:widget/stats
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StatsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var stats_default = ComponentWithRoot
export { stats_default as default }
