// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Mobile' // Variant
 * previewImage?: {src: string, srcSet?: string, alt?: string} // Preview Image
 * title?: string // Title
 * date?: string | Date // Date
 * category?: string // Category
 * link?: string // Link
}} Props

 */
import {
  className as className2,
  css as css2,
  fonts as fonts2,
} from "./chunks/chunk-VBSW7EAG.js"
import { Grain } from "./chunks/chunk-J6FBOBB4.js"
import { className, css, fonts } from "./chunks/chunk-WZ4R5HAQ.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:blog-card
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/pGAXgxPCO4nYWUjiYf5T/kr3YZW25Y3uBoIFjLlXF/mNGZ9IZwB.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleCode,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"

// /:https://framerusercontent.com/modules/HGjQpgwPDcAp1IIoblpZ/6ppJlCLw0wwX04jO3nDa/q8x7ZnCDG.js
import { fontStore } from "unframer"
fontStore.loadFonts(["GF;Manrope-regular", "GF;Manrope-700"])
var fonts3 = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_A87jxeN7B.woff2",
        weight: "400",
      },
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
        weight: "700",
      },
    ],
  },
]
var css3 = [
  '.framer-9ncDj .framer-styles-preset-l8rvat:not(.rich-text-wrapper), .framer-9ncDj .framer-styles-preset-l8rvat.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-9ncDj .framer-styles-preset-l8rvat:not(.rich-text-wrapper), .framer-9ncDj .framer-styles-preset-l8rvat.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-9ncDj .framer-styles-preset-l8rvat:not(.rich-text-wrapper), .framer-9ncDj .framer-styles-preset-l8rvat.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: 0em; --framer-line-height: 150%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: #ffffff; --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
]
var className3 = "framer-9ncDj"

// /:https://framerusercontent.com/modules/pGAXgxPCO4nYWUjiYf5T/kr3YZW25Y3uBoIFjLlXF/mNGZ9IZwB.js
var GrainFonts = getFonts(Grain)
var enabledGestures = {
  jV_vMsTtD: {
    hover: true,
  },
}
var cycleOrder = ["jV_vMsTtD", "krp2PxpJp"]
var serializationHash = "framer-Q1cJ8"
var variantClassNames = {
  jV_vMsTtD: "framer-v-1mxcq1l",
  krp2PxpJp: "framer-v-837d4p",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: "spring",
}
var toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value
  }
  return typeof value === "string"
    ? {
        src: value,
      }
    : void 0
}
var sharedDateFormatter = (value, formatOptions, locale) => {
  if (typeof value !== "string") return ""
  const date = new Date(value)
  if (isNaN(date.getTime())) return ""
  const fallbackLocale = "en-US"
  try {
    return date.toLocaleString(locale || fallbackLocale, formatOptions)
  } catch {
    return date.toLocaleString(fallbackLocale, formatOptions)
  }
}
var dateOptions = {
  dateStyle: "medium",
  timeZone: "UTC",
}
var toDateString = (value, activeLocale) => {
  return sharedDateFormatter(value, dateOptions, activeLocale)
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  "Variant 1": "jV_vMsTtD",
  Mobile: "krp2PxpJp",
}
var getProps = ({
  category,
  date,
  height,
  id,
  link,
  previewImage,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    caZHnTduO: date ?? props.caZHnTduO ?? "3025-03-12T00:00:00.000Z",
    TN31vGSU6: title ?? props.TN31vGSU6 ?? "Polestar New EV",
    uXMLoTw3x: previewImage ?? props.uXMLoTw3x,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "jV_vMsTtD",
    VvjoQT2Xh: category ?? props.VvjoQT2Xh ?? "Launch Event",
    xHnI8uC1J: link ?? props.xHnI8uC1J,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className4,
    layoutId,
    variant,
    uXMLoTw3x,
    TN31vGSU6,
    caZHnTduO,
    VvjoQT2Xh,
    xHnI8uC1J,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "jV_vMsTtD",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className2, className, className3]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const activeLocaleCode = useLocaleCode()
  const textContent = toDateString(caZHnTduO, activeLocaleCode)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={xHnI8uC1J}
            motionChild={true}
            nodeId={"jV_vMsTtD"}
            openInNewTab={false}
            scopeId={"mNGZ9IZwB"}
            smoothScroll={true}
          >
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, "framer-1mxcq1l", className4, classNames)} framer-jg197b`}
              data-border={true}
              data-framer-name={"Variant 1"}
              layoutDependency={layoutDependency}
              layoutId={"jV_vMsTtD"}
              ref={refBinding}
              style={{
                "--border-bottom-width": "0.5px",
                "--border-color":
                  "var(--token-9d9e3f83-4897-44f2-8a7e-4dd3b7f35bce, rgba(255, 255, 255, 0.5))",
                "--border-left-width": "0.5px",
                "--border-right-width": "0.5px",
                "--border-style": "solid",
                "--border-top-width": "0.5px",
                backgroundColor: "rgb(17, 17, 17)",
                ...style,
              }}
              {...addPropertyOverrides(
                {
                  "jV_vMsTtD-hover": {
                    "data-framer-name": void 0,
                  },
                  krp2PxpJp: {
                    "data-framer-name": "Mobile",
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              <motion.div
                className={"framer-1f262d2"}
                layoutDependency={layoutDependency}
                layoutId={"GZeDN_eKQ"}
              >
                <Image
                  background={{
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0 + 0 + 0
                    ),
                    sizes: componentViewport?.width || "100vw",
                    ...toResponsiveImage(uXMLoTw3x),
                  }}
                  className={"framer-1utnmxj"}
                  data-framer-name={"Main Image"}
                  layoutDependency={layoutDependency}
                  layoutId={"JszUurcHj"}
                  style={{
                    filter: "none",
                    WebkitFilter: "none",
                  }}
                  variants={{
                    "jV_vMsTtD-hover": {
                      filter: "blur(5px)",
                      WebkitFilter: "blur(5px)",
                    },
                  }}
                  {...addPropertyOverrides(
                    {
                      "jV_vMsTtD-hover": {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 0 + 0 + 0 + -42
                          ),
                          sizes: `calc(${componentViewport?.width || "100vw"} * 1.2)`,
                          ...toResponsiveImage(uXMLoTw3x),
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={"framer-1gf5tqc-container"}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={"j7mQvYtHI-container"}
                    nodeId={"j7mQvYtHI"}
                    rendersWithMotion={true}
                    scopeId={"mNGZ9IZwB"}
                    style={{
                      opacity: 0.3,
                    }}
                  >
                    <Grain
                      height={"100%"}
                      id={"j7mQvYtHI"}
                      layoutId={"j7mQvYtHI"}
                      opacity={0.09}
                      style={{
                        height: "100%",
                        width: "100%",
                      }}
                      width={"100%"}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
              <motion.div
                className={"framer-1yhrf8c"}
                data-framer-name={"info"}
                layoutDependency={layoutDependency}
                layoutId={"KfBNfQMr0"}
                style={{
                  backgroundColor:
                    "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
                }}
              >
                <motion.div
                  className={"framer-cx4qkr"}
                  data-framer-name={"container"}
                  layoutDependency={layoutDependency}
                  layoutId={"eqZG4aj3n"}
                >
                  <motion.div
                    className={"framer-o9cwb0"}
                    data-framer-name={"Top info"}
                    layoutDependency={layoutDependency}
                    layoutId={"ZSUBhjnUR"}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={"framer-8r6i2s"}
                      data-framer-name={"Product Name"}
                      fonts={["Inter"]}
                      layoutDependency={layoutDependency}
                      layoutId={"OmuuDkNGc"}
                      style={{
                        "--extracted-r6o4lv":
                          "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                        "--framer-paragraph-spacing": "0px",
                      }}
                      text={TN31vGSU6}
                      verticalAlignment={"top"}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p
                          className={"framer-styles-preset-8fr7w9"}
                          data-styles-preset={"O9KjVkdt6"}
                          style={{
                            "--framer-text-alignment": "left",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                          }}
                        >
                          {"Polestar New EV"}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                    <RichText
                      __fromCanvasComponent={true}
                      className={"framer-lrx1z5"}
                      data-framer-name={
                        "Dignissim in ullamcorper quam morbi est ipsum lectus eget. Lobortis sed elit commodo et suspendisse enim."
                      }
                      fonts={["Inter"]}
                      layoutDependency={layoutDependency}
                      layoutId={"nu6mEMrTS"}
                      style={{
                        "--extracted-r6o4lv":
                          "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                        "--framer-paragraph-spacing": "0px",
                      }}
                      text={textContent}
                      verticalAlignment={"top"}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p
                          className={"framer-styles-preset-l8z0ds"}
                          data-styles-preset={"OliekYd_C"}
                          style={{
                            "--framer-text-alignment": "left",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                          }}
                        >
                          {"Mar 12, 3025"}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                  </motion.div>
                  <motion.div
                    className={"framer-1go739i"}
                    data-border={true}
                    data-framer-name={"Category"}
                    layoutDependency={layoutDependency}
                    layoutId={"rnrBgo8Gg"}
                    style={{
                      "--border-bottom-width": "0px",
                      "--border-color":
                        "var(--token-9d9e3f83-4897-44f2-8a7e-4dd3b7f35bce, rgba(255, 255, 255, 0.5))",
                      "--border-left-width": "0.5px",
                      "--border-right-width": "0.5px",
                      "--border-style": "solid",
                      "--border-top-width": "0px",
                    }}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={"framer-1l7zep8"}
                      data-framer-name={"branding"}
                      fonts={["Inter"]}
                      layoutDependency={layoutDependency}
                      layoutId={"n05UZMq8l"}
                      style={{
                        "--extracted-r6o4lv":
                          "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                        "--framer-paragraph-spacing": "0px",
                      }}
                      text={VvjoQT2Xh}
                      verticalAlignment={"top"}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p
                          className={"framer-styles-preset-l8rvat"}
                          data-styles-preset={"q8x7ZnCDG"}
                          style={{
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                          }}
                        >
                          {"text"}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                  </motion.div>
                </motion.div>
              </motion.div>
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css4 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Q1cJ8.framer-jg197b, .framer-Q1cJ8 .framer-jg197b { display: block; }",
  ".framer-Q1cJ8.framer-1mxcq1l { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: wrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 360px; }",
  ".framer-Q1cJ8 .framer-1f262d2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 420px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Q1cJ8 .framer-1utnmxj { flex: none; height: 100%; position: relative; width: 100%; }",
  ".framer-Q1cJ8 .framer-1gf5tqc-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
  ".framer-Q1cJ8 .framer-1yhrf8c { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px; position: relative; width: 100%; }",
  ".framer-Q1cJ8 .framer-cx4qkr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-Q1cJ8 .framer-o9cwb0 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-Q1cJ8 .framer-8r6i2s, .framer-Q1cJ8 .framer-lrx1z5 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-Q1cJ8 .framer-1go739i { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 2px 10px 2px 10px; position: relative; width: min-content; }",
  ".framer-Q1cJ8 .framer-1l7zep8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Q1cJ8.framer-v-837d4p.framer-1mxcq1l { cursor: unset; }",
  ".framer-Q1cJ8.framer-v-837d4p .framer-cx4qkr { flex-direction: column; gap: 16px; }",
  ".framer-Q1cJ8.framer-v-837d4p .framer-o9cwb0 { flex: none; width: 100%; }",
  ".framer-Q1cJ8.framer-v-1mxcq1l.hover .framer-1utnmxj { height: 120%; width: 120%; }",
  ...css2,
  ...css,
  ...css3,
  '.framer-Q1cJ8[data-border="true"]::after, .framer-Q1cJ8 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
]
var FramermNGZ9IZwB = withCSS(Component, css4, "framer-Q1cJ8")
var stdin_default = FramermNGZ9IZwB
FramermNGZ9IZwB.displayName = "Blog card"
FramermNGZ9IZwB.defaultProps = {
  height: 522,
  width: 360,
}
addPropertyControls(FramermNGZ9IZwB, {
  variant: {
    options: ["jV_vMsTtD", "krp2PxpJp"],
    optionTitles: ["Variant 1", "Mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  uXMLoTw3x: {
    title: "Preview Image",
    type: ControlType.ResponsiveImage,
  },
  TN31vGSU6: {
    defaultValue: "Polestar New EV",
    title: "Title",
    type: ControlType.String,
  },
  caZHnTduO: {
    defaultValue: "3025-03-12T00:00:00.000Z",
    title: "Date",
    type: ControlType.Date,
  },
  VvjoQT2Xh: {
    defaultValue: "Launch Event",
    title: "Category",
    type: ControlType.String,
  },
  xHnI8uC1J: {
    title: "Link",
    type: ControlType.Link,
  },
})
addFonts(
  FramermNGZ9IZwB,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...GrainFonts,
    ...getFontsFromSharedStyle(fonts2),
    ...getFontsFromSharedStyle(fonts),
    ...getFontsFromSharedStyle(fonts3),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:blog-card
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {
  base: "krp2PxpJp",
  xl: "jV_vMsTtD",
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var blog_card_default = ComponentWithRoot
export { blog_card_default as default }
