// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-FGELMD25.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:built-in
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/kZS5FqPAJRMc6xNHP8JE/RCbfhmHSIOxMDoRkBviY/aQAhlMqpq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Link,
  RichText,
  SVG,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"
var enabledGestures = {
  iuWZ_PWD1: {
    hover: true,
  },
}
var serializationHash = "framer-Hh8VB"
var variantClassNames = {
  iuWZ_PWD1: "framer-v-5q6p69",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  bounce: 0.35,
  delay: 0,
  duration: 0.39,
  type: "spring",
}
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var getProps = ({ height, id, link, width, ...props }) => {
  return {
    ...props,
    ztzs9EY6t: link ?? props.ztzs9EY6t,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    ztzs9EY6t: ztzs9EY6t2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "iuWZ_PWD1",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={ztzs9EY6t2}
            motionChild={true}
            nodeId={"iuWZ_PWD1"}
            scopeId={"aQAhlMqpq"}
          >
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, "framer-5q6p69", className2, classNames)} framer-1rrrh7l`}
              data-framer-name={"Desktop"}
              layoutDependency={layoutDependency}
              layoutId={"iuWZ_PWD1"}
              ref={refBinding}
              style={{
                ...style,
              }}
              {...addPropertyOverrides(
                {
                  "iuWZ_PWD1-hover": {
                    "data-framer-name": void 0,
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              <SVG
                className={"framer-con7qj"}
                data-framer-name={"Vector"}
                fill={"rgba(0,0,0,1)"}
                intrinsicHeight={14}
                intrinsicWidth={9}
                layoutDependency={layoutDependency}
                layoutId={"bAjHQNNDB"}
                svg={
                  '<svg width="9" height="14" viewBox="0 0 9 14" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M0 0H9V4.66667H4.5L0 0ZM0 4.66667H4.5L9 9.33333H0V4.66667ZM0 9.33333H4.5V14L0 9.33333Z" fill="white"/>\n</svg>\n'
                }
                withExternalLayout={true}
              />
              <motion.div
                className={"framer-1cqmdnu"}
                data-framer-name={"Text"}
                layoutDependency={layoutDependency}
                layoutId={"HrmxIP4ls"}
              >
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-1kdk24l"}
                  fonts={["Inter"]}
                  layoutDependency={layoutDependency}
                  layoutId={"QxRaB4XQj"}
                  style={{
                    "--extracted-r6o4lv":
                      "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                  }}
                  transformTemplate={transformTemplate1}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      "iuWZ_PWD1-hover": {
                        transformTemplate: void 0,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React.Fragment>
                    <motion.p
                      className={"framer-styles-preset-17pud0k"}
                      data-styles-preset={"ihzp9MbkK"}
                      style={{
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                      }}
                    >
                      {"Built in Framer"}
                    </motion.p>
                  </React.Fragment>
                </RichText>
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-1p78zjz"}
                  fonts={["Inter"]}
                  layoutDependency={layoutDependency}
                  layoutId={"APh7k6WoT"}
                  style={{
                    "--extracted-r6o4lv":
                      "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                  }}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      "iuWZ_PWD1-hover": {
                        transformTemplate: transformTemplate1,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React.Fragment>
                    <motion.p
                      className={"framer-styles-preset-17pud0k"}
                      data-styles-preset={"ihzp9MbkK"}
                      style={{
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                      }}
                    >
                      {"Built in Framer"}
                    </motion.p>
                  </React.Fragment>
                </RichText>
              </motion.div>
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Hh8VB.framer-1rrrh7l, .framer-Hh8VB .framer-1rrrh7l { display: block; }",
  ".framer-Hh8VB.framer-5q6p69 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-Hh8VB .framer-con7qj { flex: none; height: 14px; position: relative; width: 9px; }",
  ".framer-Hh8VB .framer-1cqmdnu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-Hh8VB .framer-1kdk24l { flex: none; height: auto; left: 50%; position: absolute; top: -18px; white-space: pre; width: auto; z-index: 1; }",
  ".framer-Hh8VB .framer-1p78zjz { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Hh8VB.framer-v-5q6p69.hover .framer-1kdk24l { left: unset; position: relative; top: unset; }",
  ".framer-Hh8VB.framer-v-5q6p69.hover .framer-1p78zjz { bottom: -18px; left: 50%; position: absolute; z-index: 1; }",
  ...css,
]
var FrameraQAhlMqpq = withCSS(Component, css2, "framer-Hh8VB")
var stdin_default = FrameraQAhlMqpq
FrameraQAhlMqpq.displayName = "Built in"
FrameraQAhlMqpq.defaultProps = {
  height: 24,
  width: 121,
}
addPropertyControls(FrameraQAhlMqpq, {
  ztzs9EY6t: {
    title: "Link",
    type: ControlType.Link,
  },
})
addFonts(
  FrameraQAhlMqpq,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:built-in
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BuiltInFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var built_in_default = ComponentWithRoot
export { built_in_default as default }
