// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
 * title?: string // Title
 * visible?: boolean // Visible
}} Props

 */
import { stdin_default } from "./chunks/chunk-42RJDD6B.js"
import { Icon } from "./chunks/chunk-VIZSTQPE.js"
import "./chunks/chunk-NULYBL27.js"
import { className, css, fonts } from "./chunks/chunk-FGELMD25.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:button-form
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/wlIJy7zMmaCP7kX0qcKJ/YMMaqTXT9YTDikk80xSo/TKbyzgLYu.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"
var MotionDivWithFX = withFX(motion.div)
var TextLinkFonts = getFonts(stdin_default)
var PhosphorFonts = getFonts(Icon)
var enabledGestures = {
  j_FGf8deX: {
    hover: true,
    pressed: true,
  },
}
var cycleOrder = [
  "j_FGf8deX",
  "eMh51JZt2",
  "xKGZNSyCt",
  "n3OjiZs2f",
  "RwgSCii27",
]
var serializationHash = "framer-4RzhK"
var variantClassNames = {
  eMh51JZt2: "framer-v-z5klhx",
  j_FGf8deX: "framer-v-1vu1brt",
  n3OjiZs2f: "framer-v-7ftvj7",
  RwgSCii27: "framer-v-az872b",
  xKGZNSyCt: "framer-v-y5eg2b",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: "spring",
}
var transition2 = {
  delay: 0,
  duration: 1,
  ease: [0, 0, 1, 1],
  type: "tween",
}
var animation = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
}
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  Default: "j_FGf8deX",
  Disabled: "xKGZNSyCt",
  Error: "RwgSCii27",
  Loading: "eMh51JZt2",
  Success: "n3OjiZs2f",
}
var getProps = ({ height, id, title, visible, width, ...props }) => {
  return {
    ...props,
    imZ_3zRmZ: visible ?? props.imZ_3zRmZ ?? true,
    UBg575zAk: title ?? props.UBg575zAk ?? "Link",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "j_FGf8deX",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    UBg575zAk,
    imZ_3zRmZ,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "j_FGf8deX",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (baseVariant === "eMh51JZt2") return true
    return false
  }
  const isDisplayed1 = () => {
    if (["n3OjiZs2f", "RwgSCii27"].includes(baseVariant)) return false
    return true
  }
  const isDisplayed2 = (value) => {
    if (baseVariant === "eMh51JZt2") return false
    return value
  }
  const isDisplayed3 = () => {
    if (baseVariant === "n3OjiZs2f") return true
    return false
  }
  const isDisplayed4 = () => {
    if (baseVariant === "RwgSCii27") return true
    return false
  }
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.button
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-1vu1brt",
              className2,
              classNames
            )}
            data-border={true}
            data-framer-name={"Default"}
            data-reset={"button"}
            layoutDependency={layoutDependency}
            layoutId={"j_FGf8deX"}
            ref={refBinding}
            style={{
              "--border-bottom-width": "0.5px",
              "--border-color":
                "var(--token-9d9e3f83-4897-44f2-8a7e-4dd3b7f35bce, rgba(255, 255, 255, 0.5))",
              "--border-left-width": "0px",
              "--border-right-width": "0px",
              "--border-style": "solid",
              "--border-top-width": "0px",
              opacity: 1,
              ...style,
            }}
            variants={{
              "j_FGf8deX-hover": {
                opacity: 1,
              },
              "j_FGf8deX-pressed": {
                opacity: 1,
              },
              n3OjiZs2f: {
                opacity: 1,
              },
              RwgSCii27: {
                "--border-color": "rgba(255, 69, 69, 0.5)",
                opacity: 1,
              },
              xKGZNSyCt: {
                opacity: 0.5,
              },
            }}
            {...addPropertyOverrides(
              {
                "j_FGf8deX-hover": {
                  "data-framer-name": void 0,
                },
                "j_FGf8deX-pressed": {
                  "data-framer-name": void 0,
                },
                eMh51JZt2: {
                  "data-framer-name": "Loading",
                },
                n3OjiZs2f: {
                  "data-framer-name": "Success",
                },
                RwgSCii27: {
                  "data-framer-name": "Error",
                },
                xKGZNSyCt: {
                  "data-framer-name": "Disabled",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            {isDisplayed() && (
              <motion.div
                className={"framer-rdr87x"}
                data-framer-name={"Spinner"}
                layoutDependency={layoutDependency}
                layoutId={"Ki0GOngaN"}
                style={{
                  mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                  WebkitMask:
                    "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                }}
              >
                <MotionDivWithFX
                  __framer__loop={animation}
                  __framer__loopEffectEnabled={true}
                  __framer__loopRepeatDelay={0}
                  __framer__loopRepeatType={"loop"}
                  __framer__loopTransition={transition2}
                  __perspectiveFX={false}
                  __smartComponentFX={true}
                  __targetOpacity={1}
                  className={"framer-409pfw"}
                  data-framer-name={"Conic"}
                  layoutDependency={layoutDependency}
                  layoutId={"qvbXkHjSH"}
                  style={{
                    background:
                      "conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
                    backgroundColor: "rgb(68, 204, 255)",
                    mask: "none",
                    WebkitMask: "none",
                  }}
                  variants={{
                    eMh51JZt2: {
                      background:
                        "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
                      backgroundColor: "rgba(0, 0, 0, 0)",
                      mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                      WebkitMask:
                        "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
                    },
                  }}
                >
                  <motion.div
                    className={"framer-1a11cll"}
                    data-framer-name={"Rounding"}
                    layoutDependency={layoutDependency}
                    layoutId={"d7ZXx0RhH"}
                    style={{
                      backgroundColor: "rgb(255, 255, 255)",
                      borderBottomLeftRadius: 1,
                      borderBottomRightRadius: 1,
                      borderTopLeftRadius: 1,
                      borderTopRightRadius: 1,
                    }}
                    transformTemplate={transformTemplate1}
                  />
                </MotionDivWithFX>
              </motion.div>
            )}
            {isDisplayed1() && (
              <ComponentViewportProvider
                height={18}
                y={
                  (componentViewport?.y || 0) +
                  (15 + ((componentViewport?.height || 52) - 30 - 18) / 2)
                }
                {...addPropertyOverrides(
                  {
                    eMh51JZt2: {
                      y:
                        (componentViewport?.y || 0) +
                        (15 +
                          ((componentViewport?.height || 50) - 30 - 18) / 2),
                    },
                  },
                  baseVariant,
                  gestureVariant
                )}
              >
                <SmartComponentScopedContainer
                  className={"framer-dpdlim-container"}
                  data-framer-name={"Text"}
                  layoutDependency={layoutDependency}
                  layoutId={"uDEidXtof-container"}
                  name={"Text"}
                  nodeId={"uDEidXtof"}
                  rendersWithMotion={true}
                  scopeId={"TKbyzgLYu"}
                >
                  {_jsx(stdin_default, {
                    diiPXt8iL: UBg575zAk,
                    height: "100%",
                    id: "uDEidXtof",
                    layoutId: "uDEidXtof",
                    name: "Text",
                    width: "100%",
                  })}
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
            )}
            {isDisplayed2(imZ_3zRmZ) && (
              <ComponentViewportProvider>
                <SmartComponentScopedContainer
                  className={"framer-7t1xaf-container"}
                  isAuthoredByUser={true}
                  layoutDependency={layoutDependency}
                  layoutId={"kqcMqOBKU-container"}
                  nodeId={"kqcMqOBKU"}
                  rendersWithMotion={true}
                  scopeId={"TKbyzgLYu"}
                  style={{
                    rotate: 0,
                  }}
                  variants={{
                    "j_FGf8deX-hover": {
                      rotate: 45,
                    },
                    "j_FGf8deX-pressed": {
                      rotate: 0,
                    },
                  }}
                >
                  <Icon
                    color={"rgb(255, 255, 255)"}
                    height={"100%"}
                    iconSearch={"arrow-up-right"}
                    iconSelection={"ArrowCircleDown"}
                    id={"kqcMqOBKU"}
                    layoutId={"kqcMqOBKU"}
                    mirrored={false}
                    selectByList={false}
                    style={{
                      height: "100%",
                      width: "100%",
                    }}
                    weight={"thin"}
                    width={"100%"}
                    {...addPropertyOverrides(
                      {
                        RwgSCii27: {
                          color: "rgb(255, 69, 69)",
                        },
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  />
                </SmartComponentScopedContainer>
              </ComponentViewportProvider>
            )}
            {isDisplayed3() && (
              <RichText
                __fromCanvasComponent={true}
                className={"framer-m7qgk1"}
                fonts={["Inter"]}
                layoutDependency={layoutDependency}
                layoutId={"g18I43aKi"}
                style={{
                  "--extracted-r6o4lv":
                    "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                }}
                verticalAlignment={"top"}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={"framer-styles-preset-17pud0k"}
                    data-styles-preset={"ihzp9MbkK"}
                    style={{
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                    }}
                  >
                    {"Thank you"}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
            {isDisplayed4() && (
              <RichText
                __fromCanvasComponent={true}
                className={"framer-1czusjy"}
                fonts={["Inter"]}
                layoutDependency={layoutDependency}
                layoutId={"nXXp1C1SB"}
                style={{
                  "--extracted-r6o4lv": "rgb(255, 69, 69)",
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                }}
                verticalAlignment={"top"}
                withExternalLayout={true}
              >
                <React.Fragment>
                  <motion.p
                    className={"framer-styles-preset-17pud0k"}
                    data-styles-preset={"ihzp9MbkK"}
                    style={{
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(255, 69, 69))",
                    }}
                  >
                    {"Something went wrong"}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
          </motion.button>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-4RzhK.framer-7iylf6, .framer-4RzhK .framer-7iylf6 { display: block; }",
  ".framer-4RzhK.framer-1vu1brt { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 15px 24px 15px 24px; position: relative; width: min-content; }",
  ".framer-4RzhK .framer-rdr87x { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }",
  ".framer-4RzhK .framer-409pfw { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
  ".framer-4RzhK .framer-1a11cll { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
  ".framer-4RzhK .framer-dpdlim-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-4RzhK .framer-7t1xaf-container { flex: none; height: 22px; position: relative; width: 22px; }",
  ".framer-4RzhK .framer-m7qgk1, .framer-4RzhK .framer-1czusjy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-4RzhK.framer-v-z5klhx.framer-1vu1brt, .framer-4RzhK.framer-v-y5eg2b.framer-1vu1brt, .framer-4RzhK.framer-v-7ftvj7.framer-1vu1brt, .framer-4RzhK.framer-v-az872b.framer-1vu1brt { cursor: unset; }",
  ".framer-4RzhK.framer-v-z5klhx .framer-rdr87x { order: 1; }",
  ".framer-4RzhK.framer-v-z5klhx .framer-409pfw { overflow: hidden; }",
  ".framer-4RzhK.framer-v-z5klhx .framer-dpdlim-container { order: 0; }",
  ".framer-4RzhK.framer-v-7ftvj7 .framer-7t1xaf-container, .framer-4RzhK.framer-v-az872b .framer-7t1xaf-container { order: 3; }",
  ".framer-4RzhK.framer-v-7ftvj7 .framer-m7qgk1, .framer-4RzhK.framer-v-az872b .framer-1czusjy { order: 2; }",
  ...css,
  '.framer-4RzhK[data-border="true"]::after, .framer-4RzhK [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
]
var FramerTKbyzgLYu = withCSS(Component, css2, "framer-4RzhK")
var stdin_default2 = FramerTKbyzgLYu
FramerTKbyzgLYu.displayName = "Button Form"
FramerTKbyzgLYu.defaultProps = {
  height: 52,
  width: 109.5,
}
addPropertyControls(FramerTKbyzgLYu, {
  variant: {
    options: ["j_FGf8deX", "eMh51JZt2", "xKGZNSyCt", "n3OjiZs2f", "RwgSCii27"],
    optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
    title: "Variant",
    type: ControlType.Enum,
  },
  UBg575zAk: {
    defaultValue: "Link",
    displayTextArea: false,
    placeholder: "Link",
    title: "Title",
    type: ControlType.String,
  },
  imZ_3zRmZ: {
    defaultValue: true,
    title: "Visible",
    type: ControlType.Boolean,
  },
})
addFonts(
  FramerTKbyzgLYu,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...TextLinkFonts,
    ...PhosphorFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:button-form
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {
  base: "j_FGf8deX",
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default2}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default2)
var button_form_default = ComponentWithRoot
export { button_form_default as default }
