// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover' | 'Dark Hover' | 'Light Hover' // Variant
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-H72XBN7Q.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:circle-cursor
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/8qQhV9lVBEEWFeyM15sF/NumCuYM94DYIwUNBDzqE/stINzAije.js
import { jsx as _jsx } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"
var enabledGestures = {
  Uy8uXcLZQ: {
    pressed: true,
  },
}
var cycleOrder = ["Uy8uXcLZQ", "pJvzNQEnr", "sfd30GPPO", "xfj3H1DNU"]
var serializationHash = "framer-RuYnO"
var variantClassNames = {
  pJvzNQEnr: "framer-v-1di057k",
  sfd30GPPO: "framer-v-9trfju",
  Uy8uXcLZQ: "framer-v-1o9ei8b",
  xfj3H1DNU: "framer-v-iea65q",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
}
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var humanReadableVariantMap = {
  "Dark Hover": "sfd30GPPO",
  "Light Hover": "xfj3H1DNU",
  Default: "Uy8uXcLZQ",
  Hover: "pJvzNQEnr",
}
var getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Uy8uXcLZQ",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Uy8uXcLZQ",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (["sfd30GPPO", "xfj3H1DNU"].includes(baseVariant)) return true
    return false
  }
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-1o9ei8b",
              className2,
              classNames
            )}
            data-framer-name={"Default"}
            layoutDependency={layoutDependency}
            layoutId={"Uy8uXcLZQ"}
            ref={refBinding}
            style={{
              "--border-bottom-width": "0px",
              "--border-color": "rgba(0, 0, 0, 0)",
              "--border-left-width": "0px",
              "--border-right-width": "0px",
              "--border-style": "solid",
              "--border-top-width": "0px",
              backgroundColor: "rgb(255, 255, 255)",
              borderBottomLeftRadius: 259,
              borderBottomRightRadius: 259,
              borderTopLeftRadius: 259,
              borderTopRightRadius: 259,
              boxShadow: "none",
              ...style,
            }}
            variants={{
              "Uy8uXcLZQ-pressed": {
                "--border-bottom-width": "0px",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-top-width": "0px",
                boxShadow: "none",
              },
              sfd30GPPO: {
                "--border-bottom-width": "0.7px",
                "--border-color":
                  "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-style": "solid",
                "--border-top-width": "0.7px",
                backgroundColor: "rgba(0, 0, 0, 0)",
                borderBottomLeftRadius: 0,
                borderBottomRightRadius: 0,
                borderTopLeftRadius: 0,
                borderTopRightRadius: 0,
                boxShadow:
                  "0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.18), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.16), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.06)",
              },
              xfj3H1DNU: {
                "--border-bottom-width": "0.7px",
                "--border-color":
                  "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
                "--border-left-width": "0px",
                "--border-right-width": "0px",
                "--border-style": "solid",
                "--border-top-width": "0.7px",
                backgroundColor: "rgba(0, 0, 0, 0)",
                borderBottomLeftRadius: 0,
                borderBottomRightRadius: 0,
                borderTopLeftRadius: 0,
                borderTopRightRadius: 0,
                boxShadow:
                  "0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.18), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.16), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.06)",
              },
            }}
            {...addPropertyOverrides(
              {
                "Uy8uXcLZQ-pressed": {
                  "data-framer-name": void 0,
                },
                pJvzNQEnr: {
                  "data-framer-name": "Hover",
                },
                sfd30GPPO: {
                  "data-border": true,
                  "data-framer-name": "Dark Hover",
                },
                xfj3H1DNU: {
                  "data-border": true,
                  "data-framer-name": "Light Hover",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            {isDisplayed() && (
              <RichText
                __fromCanvasComponent={true}
                className={"framer-6851qt"}
                fonts={["GF;Instrument Sans-700"]}
                layoutDependency={layoutDependency}
                layoutId={"xdkQAhyd8"}
                style={{
                  "--framer-link-text-color": "rgb(0, 153, 255)",
                  "--framer-link-text-decoration": "underline",
                }}
                transformTemplate={transformTemplate1}
                variants={{
                  sfd30GPPO: {
                    "--extracted-r6o4lv":
                      "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  xfj3H1DNU: {
                    "--extracted-r6o4lv":
                      "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
                    "--framer-paragraph-spacing": "0px",
                  },
                }}
                verticalAlignment={"top"}
                withExternalLayout={true}
                {...addPropertyOverrides(
                  {
                    sfd30GPPO: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-10apsg8"}
                            data-styles-preset={"hmiaYBeJ7"}
                            style={{
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                            }}
                          >
                            {"view"}
                          </motion.p>
                        </React.Fragment>
                      ),
                      fonts: ["Inter"],
                      transformTemplate: void 0,
                    },
                    xfj3H1DNU: {
                      children: (
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-10apsg8"}
                            data-styles-preset={"hmiaYBeJ7"}
                            style={{
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12)))",
                            }}
                          >
                            {"view"}
                          </motion.p>
                        </React.Fragment>
                      ),
                      fonts: ["Inter"],
                      transformTemplate: void 0,
                    },
                  },
                  baseVariant,
                  gestureVariant
                )}
              >
                <React.Fragment>
                  <motion.p
                    style={{
                      "--font-selector": "R0Y7SW5zdHJ1bWVudCBTYW5zLTcwMA==",
                      "--framer-font-family":
                        '"Instrument Sans", "Instrument Sans Placeholder", sans-serif',
                      "--framer-font-size": "25px",
                      "--framer-font-weight": "700",
                      "--framer-letter-spacing": "-0.03em",
                      "--framer-line-height": "22px",
                      "--framer-text-alignment": "center",
                    }}
                  >
                    {"VIEW"}
                  </motion.p>
                </React.Fragment>
              </RichText>
            )}
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-RuYnO.framer-1gv5ayh, .framer-RuYnO .framer-1gv5ayh { display: block; }",
  ".framer-RuYnO.framer-1o9ei8b { cursor: pointer; height: 11px; mix-blend-mode: difference; overflow: hidden; position: relative; width: 10px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-RuYnO .framer-6851qt { bottom: -20px; flex: none; height: auto; left: 49%; position: absolute; white-space: pre; width: auto; }",
  ".framer-RuYnO.framer-v-1di057k.framer-1o9ei8b { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 20px); width: 20px; }",
  ".framer-RuYnO.framer-v-9trfju.framer-1o9ei8b, .framer-RuYnO.framer-v-iea65q.framer-1o9ei8b { align-content: center; align-items: center; cursor: unset; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; mix-blend-mode: unset; padding: 2px 8px 2px 8px; width: min-content; will-change: unset; }",
  ".framer-RuYnO.framer-v-9trfju .framer-6851qt, .framer-RuYnO.framer-v-iea65q .framer-6851qt { bottom: unset; left: unset; position: relative; }",
  ".framer-RuYnO.framer-v-1o9ei8b.pressed.framer-1o9ei8b { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 6px); width: 6px; }",
  ...css,
  '.framer-RuYnO[data-border="true"]::after, .framer-RuYnO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
]
var FramerstINzAije = withCSS(Component, css2, "framer-RuYnO")
var stdin_default = FramerstINzAije
FramerstINzAije.displayName = "Circle Cursor"
FramerstINzAije.defaultProps = {
  height: 10,
  width: 10,
}
addPropertyControls(FramerstINzAije, {
  variant: {
    options: ["Uy8uXcLZQ", "pJvzNQEnr", "sfd30GPPO", "xfj3H1DNU"],
    optionTitles: ["Default", "Hover", "Dark Hover", "Light Hover"],
    title: "Variant",
    type: ControlType.Enum,
  },
})
addFonts(
  FramerstINzAije,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Instrument Sans",
          source: "google",
          style: "normal",
          url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSQi_gfwmS0v3_7Y.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:circle-cursor
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CircleCursorFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var circle_cursor_default = ComponentWithRoot
export { circle_cursor_default as default }
