// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Basic' | 'Small' // Variant
 * title?: string // Title
 * background?: string // Background
 * arrow ?: boolean // arrow 
 * link?: string // Link
}} Props

 */
import {
  NullState,
  defaultEvents,
  useIconSelection,
} from "./chunks/chunk-NULYBL27.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:cta-button
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/jJI68cfGXxe4shndxgmj/M2zujKC8dDoHGq9LK3jp/usujFZ6QR.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx,
  getFonts,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React2 from "react"
import { useRef as useRef2 } from "react"

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
import { jsx as _jsx } from "react/jsx-runtime"
import * as React from "react"
import { useState, useEffect, useRef } from "react"
import { addPropertyControls, ControlType, RenderTarget } from "unframer"

// /:https://framerusercontent.com/modules/8tFVJ9SCM5akQRM0UzVD/YkxZV5bKC4LrRDEdvAgQ/home.js
var r
var s = (o) => {
  if (!r) {
    const n = o.forwardRef(
      ({ color: t = "currentColor", size: e = 24, ...i }, l) => {
        return o.createElement(
          "svg",
          {
            ref: l,
            xmlns: "http://www.w3.org/2000/svg",
            width: e,
            height: e,
            viewBox: "0 0 24 24",
            fill: "none",
            stroke: t,
            strokeWidth: "2",
            strokeLinecap: "round",
            strokeLinejoin: "round",
            ...i,
          },
          o.createElement("path", {
            d: "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
          }),
          o.createElement("polyline", {
            points: "9 22 9 12 15 12 15 22",
          })
        )
      }
    )
    ;((n.displayName = "Home"), (r = n))
  }
  return r
}

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
var iconKeys = [
  "activity",
  "airplay",
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "align-center",
  "align-justify",
  "align-left",
  "align-right",
  "anchor",
  "aperture",
  "archive",
  "arrow-down",
  "arrow-down-circle",
  "arrow-down-left",
  "arrow-down-right",
  "arrow-left",
  "arrow-left-circle",
  "arrow-right",
  "arrow-right-circle",
  "arrow-up",
  "arrow-up-circle",
  "arrow-up-left",
  "arrow-up-right",
  "at-sign",
  "award",
  "bar-chart",
  "bar-chart-2",
  "battery",
  "battery-charging",
  "bell",
  "bell-off",
  "bluetooth",
  "bold",
  "book",
  "book-open",
  "bookmark",
  "box",
  "briefcase",
  "calendar",
  "camera",
  "camera-off",
  "cast",
  "check",
  "check-circle",
  "check-square",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "chevrons-down",
  "chevrons-left",
  "chevrons-right",
  "chevrons-up",
  "chrome",
  "circle",
  "clipboard",
  "clock",
  "cloud",
  "cloud-drizzle",
  "cloud-lightning",
  "cloud-off",
  "cloud-rain",
  "cloud-snow",
  "code",
  "codepen",
  "codesandbox",
  "coffee",
  "columns",
  "command",
  "compass",
  "copy",
  "corner-down-left",
  "corner-down-right",
  "corner-left-down",
  "corner-left-up",
  "corner-right-down",
  "corner-right-up",
  "corner-up-left",
  "corner-up-right",
  "cpu",
  "credit-card",
  "crop",
  "crosshair",
  "database",
  "delete",
  "disc",
  "divide",
  "divide-circle",
  "divide-square",
  "dollar-sign",
  "download",
  "download-cloud",
  "dribbble",
  "droplet",
  "edit",
  "edit-2",
  "edit-3",
  "external-link",
  "eye",
  "eye-off",
  "facebook",
  "fast-forward",
  "feather",
  "figma",
  "file",
  "file-minus",
  "file-plus",
  "file-text",
  "film",
  "filter",
  "flag",
  "folder",
  "folder-minus",
  "folder-plus",
  "framer",
  "frown",
  "gift",
  "git-branch",
  "git-commit",
  "git-merge",
  "git-pull-request",
  "github",
  "gitlab",
  "globe",
  "grid",
  "hard-drive",
  "hash",
  "headphones",
  "heart",
  "help-circle",
  "hexagon",
  "home",
  "image",
  "inbox",
  "info",
  "instagram",
  "italic",
  "key",
  "layers",
  "layout",
  "life-buoy",
  "link",
  "link-2",
  "linkedin",
  "list",
  "loader",
  "lock",
  "log-in",
  "log-out",
  "mail",
  "map",
  "map-pin",
  "maximize",
  "maximize-2",
  "meh",
  "menu",
  "message-circle",
  "message-square",
  "mic",
  "mic-off",
  "minimize",
  "minimize-2",
  "minus",
  "minus-circle",
  "minus-square",
  "monitor",
  "moon",
  "more-horizontal",
  "more-vertical",
  "mouse-pointer",
  "move",
  "music",
  "navigation",
  "navigation-2",
  "octagon",
  "package",
  "paperclip",
  "pause",
  "pause-circle",
  "pen-tool",
  "percent",
  "phone",
  "phone-call",
  "phone-forwarded",
  "phone-incoming",
  "phone-missed",
  "phone-off",
  "phone-outgoing",
  "pie-chart",
  "play",
  "play-circle",
  "plus",
  "plus-circle",
  "plus-square",
  "pocket",
  "power",
  "printer",
  "radio",
  "refresh-ccw",
  "refresh-cw",
  "repeat",
  "rewind",
  "rotate-ccw",
  "rotate-cw",
  "rss",
  "save",
  "scissors",
  "search",
  "send",
  "server",
  "settings",
  "share",
  "share-2",
  "shield",
  "shield-off",
  "shopping-bag",
  "shopping-cart",
  "shuffle",
  "sidebar",
  "skip-back",
  "skip-forward",
  "slack",
  "slash",
  "sliders",
  "smartphone",
  "smile",
  "speaker",
  "square",
  "star",
  "stop-circle",
  "sun",
  "sunrise",
  "sunset",
  "tablet",
  "tag",
  "target",
  "terminal",
  "thermometer",
  "thumbs-down",
  "thumbs-up",
  "toggle-left",
  "toggle-right",
  "tool",
  "trash",
  "trash-2",
  "trello",
  "trending-down",
  "trending-up",
  "triangle",
  "truck",
  "tv",
  "twitch",
  "twitter",
  "type",
  "umbrella",
  "underline",
  "unlock",
  "upload",
  "upload-cloud",
  "user",
  "user-check",
  "user-minus",
  "user-plus",
  "user-x",
  "users",
  "video",
  "video-off",
  "voicemail",
  "volume",
  "volume-1",
  "volume-2",
  "volume-x",
  "watch",
  "wifi",
  "wifi-off",
  "wind",
  "x",
  "x-circle",
  "x-octagon",
  "x-square",
  "youtube",
  "zap",
  "zap-off",
  "zoom-in",
  "zoom-out",
]
var moduleBaseUrl = "https://framer.com/m/feather-icons/"
var uppercaseIconKeys = iconKeys.map(
  (name) => name.charAt(0).toUpperCase() + name.slice(1)
)
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
  res[key.toLowerCase()] = key
  return res
}, {})
function Icon(props) {
  const {
    color,
    selectByList,
    iconSearch,
    iconSelection,
    onClick,
    onMouseDown,
    onMouseUp,
    onMouseEnter,
    onMouseLeave,
    mirrored,
  } = props
  const isMounted = useRef(false)
  const iconKey = useIconSelection(
    iconKeys,
    selectByList,
    iconSearch,
    iconSelection,
    lowercaseIconKeyPairs
  )
  const [SelectedIcon, setSelectedIcon] = useState(
    iconKey === "Home" ? s(React) : null
  )
  async function importModule() {
    let active = true
    try {
      const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@0.0.29`
      const module = await import(
        /* webpackIgnore: true */
        /* @vite-ignore */
        iconModuleUrl
      )
      if (active) setSelectedIcon(module.default(React))
    } catch (e) {
      console.log(e)
      if (active) setSelectedIcon(null)
    }
    return () => {
      active = false
    }
  }
  useEffect(() => {
    importModule()
  }, [iconKey])
  const isOnCanvas = RenderTarget.current() === RenderTarget.canvas
  const emptyState = isOnCanvas ? <NullState /> : null
  return (
    <div
      style={{
        display: "contents",
      }}
      onClick={onClick}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      onMouseUp={onMouseUp}
    >
      {SelectedIcon ? (
        <SelectedIcon
          style={{
            width: "100%",
            height: "100%",
            transform: mirrored ? "scale(-1, 1)" : void 0,
          }}
          color={color}
        />
      ) : (
        emptyState
      )}
    </div>
  )
}
Icon.displayName = "Feather"
Icon.defaultProps = {
  width: 24,
  height: 24,
  iconSelection: "home",
  iconSearch: "Home",
  color: "#66F",
  selectByList: true,
  mirrored: false,
}
addPropertyControls(Icon, {
  selectByList: {
    type: ControlType.Boolean,
    title: "Select",
    enabledTitle: "List",
    disabledTitle: "Search",
    defaultValue: Icon.defaultProps.selectByList,
  },
  iconSelection: {
    type: ControlType.Enum,
    options: iconKeys,
    optionTitles: uppercaseIconKeys,
    defaultValue: Icon.defaultProps.iconSelection,
    title: "Name",
    hidden: ({ selectByList }) => !selectByList,
    description:
      "Find every icon name on the [Feather site](https://feathericons.com/)",
  },
  iconSearch: {
    type: ControlType.String,
    title: "Name",
    placeholder: "Menu, Wifi, Box\u2026",
    hidden: ({ selectByList }) => selectByList,
  },
  mirrored: {
    type: ControlType.Boolean,
    enabledTitle: "Yes",
    disabledTitle: "No",
    defaultValue: Icon.defaultProps.mirrored,
  },
  color: {
    type: ControlType.Color,
    title: "Color",
    defaultValue: Icon.defaultProps.color,
  },
  ...defaultEvents,
})

// /:https://framerusercontent.com/modules/jJI68cfGXxe4shndxgmj/M2zujKC8dDoHGq9LK3jp/usujFZ6QR.js
var FeatherFonts = getFonts(Icon)
var enabledGestures = {
  g1hXRrYlc: {
    hover: true,
  },
  Hw7NMZVXJ: {
    hover: true,
  },
}
var cycleOrder = ["Hw7NMZVXJ", "g1hXRrYlc"]
var serializationHash = "framer-EM12I"
var variantClassNames = {
  g1hXRrYlc: "framer-v-i16h90",
  Hw7NMZVXJ: "framer-v-1k8sghc",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 300,
  type: "spring",
}
var Transition = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React2.Fragment)
var humanReadableVariantMap = {
  Basic: "Hw7NMZVXJ",
  Small: "g1hXRrYlc",
}
var getProps = ({
  arrow,
  background,
  height,
  id,
  link,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    ae3kdG3b0:
      background ??
      props.ae3kdG3b0 ??
      "var(--token-a888adc2-3d05-4d6f-88b7-8dab97418795, rgb(129, 74, 200))",
    IHCtoN6iC: arrow ?? props.IHCtoN6iC ?? true,
    NAbd17i0q: title ?? props.NAbd17i0q ?? "Get in touch",
    t90xdY6CE: link ?? props.t90xdY6CE,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "Hw7NMZVXJ",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React2.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className,
    layoutId,
    variant,
    NAbd17i0q: NAbd17i0q2,
    ae3kdG3b0: ae3kdG3b02,
    IHCtoN6iC: IHCtoN6iC2,
    t90xdY6CE: t90xdY6CE2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "Hw7NMZVXJ",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = []
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={t90xdY6CE2}
            motionChild={true}
            nodeId={"Hw7NMZVXJ"}
            scopeId={"usujFZ6QR"}
            smoothScroll={true}
          >
            <motion.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, "framer-1k8sghc", className, classNames)} framer-ti7w7u`}
              data-border={true}
              data-framer-name={"Basic"}
              layoutDependency={layoutDependency}
              layoutId={"Hw7NMZVXJ"}
              ref={refBinding}
              style={{
                "--border-bottom-width": "1px",
                "--border-color":
                  "var(--token-6839e435-35f3-4ab3-b723-e98c27e525bc, rgba(255, 255, 255, 0.1))",
                "--border-left-width": "1px",
                "--border-right-width": "1px",
                "--border-style": "solid",
                "--border-top-width": "1px",
                backgroundColor: ae3kdG3b02,
                borderBottomLeftRadius: 6,
                borderBottomRightRadius: 6,
                borderTopLeftRadius: 6,
                borderTopRightRadius: 6,
                boxShadow:
                  "0px 0.7065919983928324px 0.7065919983928324px -0.625px rgba(0, 0, 0, 0.15), 0px 1.8065619053231785px 1.8065619053231785px -1.25px rgba(0, 0, 0, 0.14), 0px 3.6217592146567767px 3.6217592146567767px -1.875px rgba(0, 0, 0, 0.14), 0px 6.8655999097303715px 6.8655999097303715px -2.5px rgba(0, 0, 0, 0.13), 0px 13.646761411524492px 13.646761411524492px -3.125px rgba(0, 0, 0, 0.1), 0px 30px 30px -3.75px rgba(0, 0, 0, 0.05)",
                ...style,
              }}
              variants={{
                "Hw7NMZVXJ-hover": {
                  "--border-color": "rgba(255, 255, 255, 0.3)",
                },
              }}
              {...addPropertyOverrides(
                {
                  "g1hXRrYlc-hover": {
                    "data-framer-name": void 0,
                  },
                  "Hw7NMZVXJ-hover": {
                    "data-framer-name": void 0,
                  },
                  g1hXRrYlc: {
                    "data-framer-name": "Small",
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              <motion.div
                className={"framer-jqoy45"}
                data-framer-name={"Text Container"}
                layoutDependency={layoutDependency}
                layoutId={"W4i57zlEY"}
              >
                <motion.div
                  className={"framer-1705ys0"}
                  data-framer-name={"1st state"}
                  layoutDependency={layoutDependency}
                  layoutId={"Z8RomRChM"}
                >
                  <RichText
                    __fromCanvasComponent={true}
                    className={"framer-vkvfc7"}
                    fonts={["GF;Figtree-500"]}
                    layoutDependency={layoutDependency}
                    layoutId={"kB5ttFvh4"}
                    style={{
                      "--extracted-r6o4lv":
                        "var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                      "--framer-paragraph-spacing": "0px",
                    }}
                    text={NAbd17i0q2}
                    verticalAlignment={"top"}
                    withExternalLayout={true}
                    {...addPropertyOverrides(
                      {
                        g1hXRrYlc: {
                          children: (
                            <React2.Fragment>
                              <motion.p
                                style={{
                                  "--font-selector": "R0Y7RmlndHJlZS01MDA=",
                                  "--framer-font-family":
                                    '"Figtree", "Figtree Placeholder", sans-serif',
                                  "--framer-font-size": "14px",
                                  "--framer-font-weight": "500",
                                  "--framer-letter-spacing": "-0.02em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255)))",
                                }}
                              >
                                {"Get in touch"}
                              </motion.p>
                            </React2.Fragment>
                          ),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  >
                    <React2.Fragment>
                      <motion.p
                        style={{
                          "--font-selector": "R0Y7RmlndHJlZS01MDA=",
                          "--framer-font-family":
                            '"Figtree", "Figtree Placeholder", sans-serif',
                          "--framer-font-size": "15px",
                          "--framer-font-weight": "500",
                          "--framer-letter-spacing": "-0.04em",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255)))",
                        }}
                      >
                        {"Get in touch"}
                      </motion.p>
                    </React2.Fragment>
                  </RichText>
                  {IHCtoN6iC2 !== false && (
                    <ComponentViewportProvider>
                      <SmartComponentScopedContainer
                        className={"framer-jzgw7o-container"}
                        isAuthoredByUser={true}
                        isModuleExternal={true}
                        layoutDependency={layoutDependency}
                        layoutId={"DlF2EaPB3-container"}
                        nodeId={"DlF2EaPB3"}
                        rendersWithMotion={true}
                        scopeId={"usujFZ6QR"}
                      >
                        <Icon
                          color={
                            "var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255))"
                          }
                          height={"100%"}
                          iconSearch={"arrow-up-right"}
                          iconSelection={"arrow-up-right"}
                          id={"DlF2EaPB3"}
                          layoutId={"DlF2EaPB3"}
                          mirrored={false}
                          selectByList={true}
                          style={{
                            height: "100%",
                            width: "100%",
                          }}
                          width={"100%"}
                        />
                      </SmartComponentScopedContainer>
                    </ComponentViewportProvider>
                  )}
                </motion.div>
                <motion.div
                  className={"framer-31lofv"}
                  data-framer-name={"2nd state"}
                  layoutDependency={layoutDependency}
                  layoutId={"HtEadH5WT"}
                >
                  <RichText
                    __fromCanvasComponent={true}
                    className={"framer-f6vbf9"}
                    fonts={["GF;Figtree-500"]}
                    layoutDependency={layoutDependency}
                    layoutId={"Ds13xPeOk"}
                    style={{
                      "--extracted-r6o4lv":
                        "var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255))",
                      "--framer-link-text-color": "rgb(0, 153, 255)",
                      "--framer-link-text-decoration": "underline",
                      "--framer-paragraph-spacing": "0px",
                    }}
                    text={NAbd17i0q2}
                    verticalAlignment={"top"}
                    withExternalLayout={true}
                    {...addPropertyOverrides(
                      {
                        g1hXRrYlc: {
                          children: (
                            <React2.Fragment>
                              <motion.p
                                style={{
                                  "--font-selector": "R0Y7RmlndHJlZS01MDA=",
                                  "--framer-font-family":
                                    '"Figtree", "Figtree Placeholder", sans-serif',
                                  "--framer-font-size": "14px",
                                  "--framer-font-weight": "500",
                                  "--framer-letter-spacing": "-0.02em",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255)))",
                                }}
                              >
                                {"Get in touch"}
                              </motion.p>
                            </React2.Fragment>
                          ),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  >
                    <React2.Fragment>
                      <motion.p
                        style={{
                          "--font-selector": "R0Y7RmlndHJlZS01MDA=",
                          "--framer-font-family":
                            '"Figtree", "Figtree Placeholder", sans-serif',
                          "--framer-font-size": "15px",
                          "--framer-font-weight": "500",
                          "--framer-letter-spacing": "-0.04em",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255)))",
                        }}
                      >
                        {"Get in touch"}
                      </motion.p>
                    </React2.Fragment>
                  </RichText>
                  {IHCtoN6iC2 !== false && (
                    <ComponentViewportProvider>
                      <SmartComponentScopedContainer
                        className={"framer-1jrwfj4-container"}
                        isAuthoredByUser={true}
                        isModuleExternal={true}
                        layoutDependency={layoutDependency}
                        layoutId={"Zk3KZe_7H-container"}
                        nodeId={"Zk3KZe_7H"}
                        rendersWithMotion={true}
                        scopeId={"usujFZ6QR"}
                      >
                        <Icon
                          color={
                            "var(--token-55fce8bf-ab86-42dc-8b77-6335cf9cf588, rgb(255, 255, 255))"
                          }
                          height={"100%"}
                          iconSearch={"arrow-up-right"}
                          iconSelection={"arrow-right"}
                          id={"Zk3KZe_7H"}
                          layoutId={"Zk3KZe_7H"}
                          mirrored={false}
                          selectByList={true}
                          style={{
                            height: "100%",
                            width: "100%",
                          }}
                          width={"100%"}
                        />
                      </SmartComponentScopedContainer>
                    </ComponentViewportProvider>
                  )}
                </motion.div>
              </motion.div>
            </motion.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-EM12I.framer-ti7w7u, .framer-EM12I .framer-ti7w7u { display: block; }",
  ".framer-EM12I.framer-1k8sghc { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 9px 13px 9px 13px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-EM12I .framer-jqoy45 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 18px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-EM12I .framer-1705ys0, .framer-EM12I .framer-31lofv { align-content: flex-end; align-items: flex-end; align-self: stretch; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }",
  ".framer-EM12I .framer-vkvfc7, .framer-EM12I .framer-f6vbf9 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-EM12I .framer-jzgw7o-container, .framer-EM12I .framer-1jrwfj4-container { flex: none; height: 16px; position: relative; width: 16px; }",
  ".framer-EM12I.framer-v-i16h90 .framer-jqoy45 { height: 17px; }",
  ".framer-EM12I.framer-v-1k8sghc.hover .framer-jqoy45, .framer-EM12I.framer-v-i16h90.hover .framer-jqoy45 { justify-content: flex-end; }",
  '.framer-EM12I[data-border="true"]::after, .framer-EM12I [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
]
var FramerusujFZ6QR = withCSS(Component, css, "framer-EM12I")
var stdin_default = FramerusujFZ6QR
FramerusujFZ6QR.displayName = "CTA Button"
FramerusujFZ6QR.defaultProps = {
  height: 36,
  width: 124,
}
addPropertyControls2(FramerusujFZ6QR, {
  variant: {
    options: ["Hw7NMZVXJ", "g1hXRrYlc"],
    optionTitles: ["Basic", "Small"],
    title: "Variant",
    type: ControlType2.Enum,
  },
  NAbd17i0q: {
    defaultValue: "Get in touch",
    displayTextArea: false,
    title: "Title",
    type: ControlType2.String,
  },
  ae3kdG3b0: {
    defaultValue:
      'var(--token-a888adc2-3d05-4d6f-88b7-8dab97418795, rgb(129, 74, 200)) /* {"name":"Purple"} */',
    title: "Background",
    type: ControlType2.Color,
  },
  IHCtoN6iC: {
    defaultValue: true,
    title: "arrow ",
    type: ControlType2.Boolean,
  },
  t90xdY6CE: {
    title: "Link",
    type: ControlType2.Link,
  },
})
addFonts(
  FramerusujFZ6QR,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Figtree",
          source: "google",
          style: "normal",
          uiFamilyName: "Figtree",
          url: "https://fonts.gstatic.com/s/figtree/v9/_Xmz-HUzqDCFdgfMsYiV_F7wfS-Bs_dNQF5bwkEU4HTy.woff2",
          weight: "500",
        },
      ],
    },
    ...FeatherFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:cta-button
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var cta_button_default = ComponentWithRoot
export { cta_button_default as default }
