// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop ' | 'Mobile ' // Variant
 * tap?: Function // Tap
 * hover?: Function // Hover
}} Props

 */
import { stdin_default } from "./chunks/chunk-GLVBB4KT.js"
import "./chunks/chunk-X4FI3VAJ.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:navigation-bar
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/mG5BAs9m8AqWCbe6x5St/p5erUhb3ATUZfSC9qTXl/qdXv6wfeK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  RichText,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"

// /:https://framerusercontent.com/modules/lHaNdv6tBgDb6y5JVk6w/2WKsTITMNdd15V2cqHHv/Cq4dW9ySa.js
import { fontStore } from "unframer"
fontStore.loadFonts(["GF;Manrope-regular", "GF;Manrope-700"])
var fonts = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_A87jxeN7B.woff2",
        weight: "400",
      },
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
        weight: "700",
      },
    ],
  },
]
var css = [
  '.framer-D2oga .framer-styles-preset-12rmaf3:not(.rich-text-wrapper), .framer-D2oga .framer-styles-preset-12rmaf3.rich-text-wrapper h3 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 130%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-D2oga .framer-styles-preset-12rmaf3:not(.rich-text-wrapper), .framer-D2oga .framer-styles-preset-12rmaf3.rich-text-wrapper h3 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 130%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-D2oga .framer-styles-preset-12rmaf3:not(.rich-text-wrapper), .framer-D2oga .framer-styles-preset-12rmaf3.rich-text-wrapper h3 { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 130%; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
]
var className = "framer-D2oga"

// /:https://framerusercontent.com/modules/mG5BAs9m8AqWCbe6x5St/p5erUhb3ATUZfSC9qTXl/qdXv6wfeK.js
var MenuButtonFonts = getFonts(stdin_default)
var MotionNavWithFX = withFX(motion.nav)
var cycleOrder = ["f9OFkvqmp", "kM2YKfLJP"]
var serializationHash = "framer-E7Muz"
var variantClassNames = {
  f9OFkvqmp: "framer-v-2nvn7f",
  kM2YKfLJP: "framer-v-1uufw0a",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  damping: 35,
  delay: 0,
  mass: 1,
  stiffness: 400,
  type: "spring",
}
var animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transformPerspective: 1200,
  x: 0,
  y: -64,
}
var transition2 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
}
var matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg
  }
  return void 0
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var humanReadableVariantMap = {
  "Desktop ": "f9OFkvqmp",
  "Mobile ": "kM2YKfLJP",
}
var Variants = motion.create(React.Fragment)
var getProps = ({ height, hover, id, tap, width, ...props }) => {
  return {
    ...props,
    LlGjrvFdC: tap ?? props.LlGjrvFdC,
    SSGmecJsf: hover ?? props.SSGmecJsf,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "f9OFkvqmp",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    LlGjrvFdC: LlGjrvFdC2,
    SSGmecJsf: SSGmecJsf2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "f9OFkvqmp",
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const onMouseEnter1kr4ncg = activeVariantCallback(async (...args) => {
    setGestureState({
      isHovered: true,
    })
    if (SSGmecJsf2) {
      const res = await SSGmecJsf2(...args)
      if (res === false) return false
    }
  })
  const Vpc2QumxM3o4osd = activeVariantCallback(async (...args) => {
    if (LlGjrvFdC2) {
      const res = await LlGjrvFdC2(...args)
      if (res === false) return false
    }
  })
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition2}>
          <MotionNavWithFX
            {...restProps}
            {...gestureHandlers}
            __framer__animate={{
              transition: transition1,
            }}
            __framer__animateOnce={false}
            __framer__scrollDirection={{
              direction: "down",
              target: animation,
            }}
            __framer__styleAppearEffectEnabled={true}
            __framer__threshold={0.5}
            __perspectiveFX={false}
            __smartComponentFX={true}
            __targetOpacity={1}
            className={cx(
              scopingClassNames,
              "framer-2nvn7f",
              className2,
              classNames
            )}
            data-framer-name={"Desktop "}
            data-highlight={true}
            layoutDependency={layoutDependency}
            layoutId={"f9OFkvqmp"}
            onMouseEnter={onMouseEnter1kr4ncg}
            ref={refBinding}
            style={{
              ...style,
            }}
            {...addPropertyOverrides(
              {
                kM2YKfLJP: {
                  "data-framer-name": "Mobile ",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            <motion.div
              className={"framer-12w0axq"}
              data-framer-name={"Container"}
              layoutDependency={layoutDependency}
              layoutId={"HMIq9pbyn"}
            >
              <motion.div
                className={"framer-aliyon"}
                data-framer-name={"Logo"}
                layoutDependency={layoutDependency}
                layoutId={"ncAYzyWFb"}
              >
                <SVG
                  className={"framer-8ajr9q"}
                  layoutDependency={layoutDependency}
                  layoutId={"fATnkogHn"}
                  requiresOverflowVisible={false}
                  svg={
                    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25.51 42.003" overflow="visible"><path d="M 23.633 17.185 L 20.341 19.571 L 23.736 22.181 C 24.846 23.038 25.51 24.384 25.51 25.791 L 25.51 29.981 C 25.51 31.431 24.816 32.801 23.65 33.657 L 12.242 42.003 L 4.522 36.84 L 16.999 28.611 L 16.999 31.507 L 8.893 36.857 L 12.179 39.053 L 22.228 31.701 C 22.773 31.301 23.099 30.658 23.099 29.981 L 23.099 25.791 C 23.099 25.135 22.79 24.502 22.269 24.102 L 17 20.052 L 16.303 19.516 L 17 19.009 L 22.223 15.225 C 22.773 14.823 23.099 14.182 23.1 13.499 L 23.1 9.942 C 23.1 9.189 22.694 8.482 22.043 8.103 L 12.963 2.813 L 2.412 9.229 L 2.412 29.893 L 8.122 26.2 L 8.122 16.941 L 16.999 11.419 L 16.999 14.265 L 10.534 18.287 L 10.534 27.516 L 0 34.336 L 0 7.866 L 12.94 0 L 23.255 6.009 C 24.647 6.823 25.51 8.329 25.51 9.942 L 25.51 13.498 C 25.51 14.955 24.81 16.334 23.633 17.184 Z" fill="rgb(255,255,255)"></path></svg>'
                  }
                  withExternalLayout={true}
                />
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-1y7wk8d"}
                  data-framer-name={"Name"}
                  fonts={["Inter"]}
                  layoutDependency={layoutDependency}
                  layoutId={"hMy4ApVod"}
                  style={{
                    "--framer-paragraph-spacing": "0px",
                  }}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                >
                  <React.Fragment>
                    <motion.h3
                      className={"framer-styles-preset-12rmaf3"}
                      data-styles-preset={"Cq4dW9ySa"}
                      dir={"auto"}
                    >
                      {"Bibotecture"}
                    </motion.h3>
                  </React.Fragment>
                </RichText>
              </motion.div>
              <motion.div
                className={"framer-1kzia1n"}
                data-framer-name={"Menu Button"}
                layoutDependency={layoutDependency}
                layoutId={"OiqW96fUR"}
              >
                <ComponentViewportProvider
                  height={54}
                  y={
                    (componentViewport?.y || 0) +
                    10 +
                    (((componentViewport?.height || 74) - 20 - 54) / 2 +
                      0 +
                      0) +
                    0 +
                    0
                  }
                >
                  <SmartComponentScopedContainer
                    className={"framer-18dg4eo-container"}
                    layoutDependency={layoutDependency}
                    layoutId={"PsOjo027O-container"}
                    nodeId={"PsOjo027O"}
                    rendersWithMotion={true}
                    scopeId={"qdXv6wfeK"}
                  >
                    {_jsx(stdin_default, {
                      C_0i5Cn_A: true,
                      height: "100%",
                      id: "PsOjo027O",
                      layoutId: "PsOjo027O",
                      variant: matchVariant("HE8ZdPn8Z"),
                      Vpc2QumxM: Vpc2QumxM3o4osd,
                      width: "100%",
                      xdx3z8nWJ: "menu",
                    })}
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
            </motion.div>
          </MotionNavWithFX>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-E7Muz.framer-yjats6, .framer-E7Muz .framer-yjats6 { display: block; }",
  ".framer-E7Muz.framer-2nvn7f { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 33px; height: min-content; justify-content: center; mix-blend-mode: difference; overflow: hidden; padding: 10px 0px 10px 0px; position: relative; width: 1440px; }",
  ".framer-E7Muz .framer-12w0axq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 30px 0px 30px; position: relative; width: 100%; }",
  ".framer-E7Muz .framer-aliyon { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: 50px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-E7Muz .framer-8ajr9q { height: 42px; position: relative; width: 26px; }",
  ".framer-E7Muz .framer-1y7wk8d { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-E7Muz .framer-1kzia1n { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 240px; }",
  ".framer-E7Muz .framer-18dg4eo-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-E7Muz.framer-v-1uufw0a.framer-2nvn7f { width: 390px; }",
  ".framer-E7Muz.framer-v-1uufw0a .framer-12w0axq { padding: 0px 16px 0px 16px; }",
  ".framer-E7Muz.framer-v-1uufw0a .framer-aliyon { gap: 24px; }",
  ".framer-E7Muz.framer-v-1uufw0a .framer-8ajr9q { order: 0; }",
  ".framer-E7Muz.framer-v-1uufw0a .framer-1y7wk8d { order: 1; }",
  ".framer-E7Muz.framer-v-1uufw0a .framer-1kzia1n { width: min-content; }",
  ...css,
]
var FramerqdXv6wfeK = withCSS(Component, css2, "framer-E7Muz")
var stdin_default2 = FramerqdXv6wfeK
FramerqdXv6wfeK.displayName = "Navigation Bar"
FramerqdXv6wfeK.defaultProps = {
  height: 74,
  width: 1440,
}
addPropertyControls(FramerqdXv6wfeK, {
  variant: {
    options: ["f9OFkvqmp", "kM2YKfLJP"],
    optionTitles: ["Desktop ", "Mobile "],
    title: "Variant",
    type: ControlType.Enum,
  },
  LlGjrvFdC: {
    title: "Tap",
    type: ControlType.EventHandler,
  },
  SSGmecJsf: {
    title: "Hover",
    type: ControlType.EventHandler,
  },
})
addFonts(
  FramerqdXv6wfeK,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...MenuButtonFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)
FramerqdXv6wfeK.loader = {
  load: (props, context) => {
    const locale = context.locale
    return Promise.allSettled([forwardLoader(stdin_default, {}, context)])
  },
}

// virtual:navigation-bar
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {
  base: "kM2YKfLJP",
  xl: "f9OFkvqmp",
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationBarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default2}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default2)
var navigation_bar_default = ComponentWithRoot
export { navigation_bar_default as default }
