// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * aILayerForShip?: string // AI layer for ship
 * onkW7SCEOgTCHange?: any // onkW7SCEOgTCHange
 * subtitle?: string // Subtitle
 * onE3l1VhsBNCHange?: any // onE3l1VhsBNCHange
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-7Z7P6UTP.js"
import { Grain } from "./chunks/chunk-J6FBOBB4.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:project-card
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/erbM8xcc9yAXPs2quDhJ/ZqdsmWxV0zLhE2CDps3K/QVEORUe9s.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"

// /:https://framerusercontent.com/modules/8eKsVLqJpwqgWvesiMU7/gqgW9WL6TTqZt0TeRrxq/OliekYd_C.js
import { fontStore } from "unframer"
fontStore.loadFonts(["GF;Manrope-300", "GF;Manrope-regular"])
var fonts2 = [
  {
    explicitInter: true,
    fonts: [
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk6jFO_A87jxeN7B.woff2",
        weight: "300",
      },
      {
        family: "Manrope",
        source: "google",
        style: "normal",
        url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk79FO_A87jxeN7B.woff2",
        weight: "400",
      },
    ],
  },
]
var css2 = [
  '.framer-HKNnt .framer-styles-preset-l8z0ds:not(.rich-text-wrapper), .framer-HKNnt .framer-styles-preset-l8z0ds.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 170%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
  '@media (max-width: 1199px) and (min-width: 810px) { .framer-HKNnt .framer-styles-preset-l8z0ds:not(.rich-text-wrapper), .framer-HKNnt .framer-styles-preset-l8z0ds.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 17px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 170%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
  '@media (max-width: 809px) and (min-width: 0px) { .framer-HKNnt .framer-styles-preset-l8z0ds:not(.rich-text-wrapper), .framer-HKNnt .framer-styles-preset-l8z0ds.rich-text-wrapper p { --framer-font-family: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-family-bold: "Manrope", "Manrope Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 15px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-variation-axes: normal; --framer-font-weight: 300; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 170%; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
]
var className2 = "framer-HKNnt"

// /:https://framerusercontent.com/modules/erbM8xcc9yAXPs2quDhJ/ZqdsmWxV0zLhE2CDps3K/QVEORUe9s.js
var GrainFonts = getFonts(Grain)
var enabledGestures = {
  tFpyyQLPI: {
    hover: true,
  },
}
var cycleOrder = ["tFpyyQLPI", "tqj96c0XF"]
var serializationHash = "framer-2mEro"
var variantClassNames = {
  tFpyyQLPI: "framer-v-1s2xigy",
  tqj96c0XF: "framer-v-u4awqh",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  delay: 0.1,
  duration: 0.4,
  ease: [0.64, 0, 0.38, 1],
  type: "tween",
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var humanReadableVariantMap = {
  Desktop: "tFpyyQLPI",
  Mobile: "tqj96c0XF",
}
var Variants = motion.create(React.Fragment)
var getProps = ({ aILayerForShip, height, id, subtitle, width, ...props }) => {
  return {
    ...props,
    E3l1VhsBN:
      subtitle ??
      props.E3l1VhsBN ??
      "The first public face of an AI-for-chip-design startup, shipped with their $1.7M funding announcement.",
    kW7SCeOgT: aILayerForShip ?? props.kW7SCeOgT,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "tFpyyQLPI",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className3,
    layoutId,
    variant,
    kW7SCeOgT: kW7SCeOgT2,
    E3l1VhsBN: E3l1VhsBN2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "tFpyyQLPI",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className2, className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={"chrome://extensions/?id=fplflkdgjbppcchgjngfleablddcannj"}
            motionChild={true}
            nodeId={"tFpyyQLPI"}
            openInNewTab={true}
            scopeId={"QVEORUe9s"}
          >
            <Image1
              {...restProps}
              {...gestureHandlers}
              as={"a"}
              background={{
                alt: "",
                fit: "fill",
                sizes: componentViewport?.width || "100vw",
              }}
              className={`${cx(scopingClassNames, "framer-1s2xigy", className3, classNames)} framer-13r8fuo`}
              data-border={true}
              data-framer-name={"Desktop"}
              layoutDependency={layoutDependency}
              layoutId={"tFpyyQLPI"}
              ref={refBinding}
              style={{
                "--border-bottom-width": "0.5px",
                "--border-color":
                  "var(--token-9d9e3f83-4897-44f2-8a7e-4dd3b7f35bce, rgba(255, 255, 255, 0.5))",
                "--border-left-width": "0.5px",
                "--border-right-width": "0.5px",
                "--border-style": "solid",
                "--border-top-width": "0.5px",
                ...style,
              }}
              {...addPropertyOverrides(
                {
                  "tFpyyQLPI-hover": {
                    "data-framer-name": void 0,
                  },
                  tqj96c0XF: {
                    "data-framer-name": "Mobile",
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              <motion.div
                className={"framer-1vpchyi"}
                layoutDependency={layoutDependency}
                layoutId={"UUUx9869Y"}
              >
                <Image1
                  background={{
                    alt: "",
                    fit: "fit",
                    intrinsicHeight: 1496,
                    intrinsicWidth: 2872,
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 0 + 0 + 0 + 0
                    ),
                    pixelHeight: 1496,
                    pixelWidth: 2872,
                    positionX: "center",
                    positionY: "center",
                    sizes: componentViewport?.width || "100vw",
                    src: "https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?width=2872&height=1496",
                    srcSet:
                      "https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=512&width=2872&height=1496 512w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=1024&width=2872&height=1496 1024w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=2048&width=2872&height=1496 2048w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?width=2872&height=1496 2872w",
                  }}
                  className={"framer-1c6a7t3"}
                  data-framer-name={"Main Image"}
                  layoutDependency={layoutDependency}
                  layoutId={"an4o3tfSb"}
                  style={{
                    filter: "none",
                    WebkitFilter: "none",
                  }}
                  variants={{
                    "tFpyyQLPI-hover": {
                      filter: "blur(5px)",
                      WebkitFilter: "blur(5px)",
                    },
                  }}
                  {...addPropertyOverrides(
                    {
                      "tFpyyQLPI-hover": {
                        background: {
                          alt: "",
                          fit: "fit",
                          intrinsicHeight: 1496,
                          intrinsicWidth: 2872,
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 0 + 0 + 0 + -42
                          ),
                          pixelHeight: 1496,
                          pixelWidth: 2872,
                          positionX: "center",
                          positionY: "center",
                          sizes: `calc(${componentViewport?.width || "100vw"} * 1.2)`,
                          src: "https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?width=2872&height=1496",
                          srcSet:
                            "https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=512&width=2872&height=1496 512w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=1024&width=2872&height=1496 1024w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?scale-down-to=2048&width=2872&height=1496 2048w,https://framerusercontent.com/images/1LunH8zTNILLueQxMpCsn4vEUo.png?width=2872&height=1496 2872w",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                />
                <ComponentViewportProvider>
                  <SmartComponentScopedContainer
                    className={"framer-18t2jdx-container"}
                    isAuthoredByUser={true}
                    isModuleExternal={true}
                    layoutDependency={layoutDependency}
                    layoutId={"HQhOJOhe_-container"}
                    nodeId={"HQhOJOhe_"}
                    rendersWithMotion={true}
                    scopeId={"QVEORUe9s"}
                    style={{
                      opacity: 0.3,
                    }}
                  >
                    <Grain
                      height={"100%"}
                      id={"HQhOJOhe_"}
                      layoutId={"HQhOJOhe_"}
                      opacity={0.09}
                      style={{
                        height: "100%",
                        width: "100%",
                      }}
                      width={"100%"}
                    />
                  </SmartComponentScopedContainer>
                </ComponentViewportProvider>
              </motion.div>
              <motion.div
                className={"framer-akdku2"}
                data-framer-name={"info"}
                layoutDependency={layoutDependency}
                layoutId={"tt9lJZYaY"}
                style={{
                  backgroundColor:
                    "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
                }}
              >
                <motion.div
                  className={"framer-ass0vn"}
                  data-framer-name={"container"}
                  layoutDependency={layoutDependency}
                  layoutId={"wg8u2zPgJ"}
                >
                  <motion.div
                    className={"framer-1x3cuxa"}
                    data-framer-name={"Top info"}
                    layoutDependency={layoutDependency}
                    layoutId={"nOMMS45Eu"}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={"framer-8mmvnq"}
                      data-framer-name={
                        "Dignissim in ullamcorper quam morbi est ipsum lectus eget. Lobortis sed elit commodo et suspendisse enim."
                      }
                      fonts={["Inter"]}
                      layoutDependency={layoutDependency}
                      layoutId={"kj4X1qBuw"}
                      style={{
                        "--extracted-r6o4lv":
                          "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                        "--framer-paragraph-spacing": "0px",
                      }}
                      text={E3l1VhsBN2}
                      verticalAlignment={"top"}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p
                          className={"framer-styles-preset-l8z0ds"}
                          data-styles-preset={"OliekYd_C"}
                          style={{
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                          }}
                        >
                          {
                            "Mobile app that helps users discover, book, and manage flights with real-time updates and seamless UX."
                          }
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                  </motion.div>
                  <motion.div
                    className={"framer-1ghrpyp"}
                    data-border={true}
                    data-framer-name={"Category"}
                    layoutDependency={layoutDependency}
                    layoutId={"SxydbfPES"}
                    style={{
                      "--border-bottom-width": "0px",
                      "--border-color":
                        "var(--token-9d9e3f83-4897-44f2-8a7e-4dd3b7f35bce, rgba(255, 255, 255, 0.5))",
                      "--border-left-width": "0.5px",
                      "--border-right-width": "0.5px",
                      "--border-style": "solid",
                      "--border-top-width": "0px",
                    }}
                  >
                    <RichText
                      __fromCanvasComponent={true}
                      className={"framer-2rkcfu"}
                      data-framer-name={"branding"}
                      fonts={["Inter"]}
                      layoutDependency={layoutDependency}
                      layoutId={"lObtGnsqV"}
                      style={{
                        "--extracted-r6o4lv":
                          "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                        "--framer-paragraph-spacing": "0px",
                      }}
                      text={kW7SCeOgT2}
                      verticalAlignment={"top"}
                      withExternalLayout={true}
                    >
                      <React.Fragment>
                        <motion.p
                          className={"framer-styles-preset-l8rvat"}
                          data-styles-preset={"q8x7ZnCDG"}
                          style={{
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                          }}
                        >
                          {"text"}
                        </motion.p>
                      </React.Fragment>
                    </RichText>
                  </motion.div>
                </motion.div>
              </motion.div>
            </Image1>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css3 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-2mEro.framer-13r8fuo, .framer-2mEro .framer-13r8fuo { display: block; }",
  ".framer-2mEro.framer-1s2xigy { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: wrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 570px; will-change: var(--framer-will-change-filter-override, filter); }",
  ".framer-2mEro .framer-1vpchyi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 420px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-2mEro .framer-1c6a7t3 { flex: none; height: 100%; position: relative; width: 100%; }",
  ".framer-2mEro .framer-18t2jdx-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 1; }",
  ".framer-2mEro .framer-akdku2 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 30px 20px 30px; position: relative; width: 100%; }",
  ".framer-2mEro .framer-ass0vn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-2mEro .framer-1x3cuxa { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-2mEro .framer-8mmvnq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-2mEro .framer-1ghrpyp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 2px 10px 2px 10px; position: relative; width: min-content; }",
  ".framer-2mEro .framer-2rkcfu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-2mEro.framer-v-u4awqh.framer-1s2xigy { cursor: unset; width: 320px; }",
  ".framer-2mEro.framer-v-u4awqh .framer-1vpchyi { height: 400px; }",
  ".framer-2mEro.framer-v-u4awqh .framer-1x3cuxa { gap: 12px; }",
  ".framer-2mEro.framer-v-1s2xigy.hover .framer-1c6a7t3 { height: 120%; width: 120%; }",
  ...css2,
  ...css,
  '.framer-2mEro[data-border="true"]::after, .framer-2mEro [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
]
var FramerQVEORUe9s = withCSS(Component, css3, "framer-2mEro")
var stdin_default = FramerQVEORUe9s
FramerQVEORUe9s.displayName = "Project card"
FramerQVEORUe9s.defaultProps = {
  height: 548,
  width: 570,
}
addPropertyControls(FramerQVEORUe9s, {
  variant: {
    options: ["tFpyyQLPI", "tqj96c0XF"],
    optionTitles: ["Desktop", "Mobile"],
    title: "Variant",
    type: ControlType.Enum,
  },
  kW7SCeOgT: {
    defaultValue: "",
    title: "AI layer for ship",
    type: ControlType.String,
  },
  onkW7SCeOgTChange: {
    changes: "kW7SCeOgT",
    type: ControlType.ChangeHandler,
  },
  E3l1VhsBN: {
    defaultValue:
      "The first public face of an AI-for-chip-design startup, shipped with their $1.7M funding announcement.",
    title: "Subtitle",
    type: ControlType.String,
  },
  onE3l1VhsBNChange: {
    changes: "E3l1VhsBN",
    type: ControlType.ChangeHandler,
  },
})
addFonts(
  FramerQVEORUe9s,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...GrainFonts,
    ...getFontsFromSharedStyle(fonts2),
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:project-card
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {
  base: "tFpyyQLPI",
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var project_card_default = ComponentWithRoot
export { project_card_default as default }
