// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'New' | 'Off' // Variant
 * price?: string // Price
 * onMSLKTJaNCHange?: any // onMSLKTJaNCHange
 * link?: string // Link
}} Props

 */
import { Icon } from "./chunks/chunk-VIZSTQPE.js"
import {
  NullState,
  defaultEvents,
  useIconSelection,
} from "./chunks/chunk-NULYBL27.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:purchase-button
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/rQAyZW1LF2z2C0hJOyNM/5gomtQ1CIfUmbhMUAJt7/NEZBs7an1.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls as addPropertyControls2,
  ComponentViewportProvider,
  ControlType as ControlType2,
  cx,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer"
import * as React2 from "react"
import { useRef as useRef2 } from "react"

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js
import { jsx as _jsx } from "react/jsx-runtime"
import * as React from "react"
import { useState, useEffect, useRef } from "react"
import { addPropertyControls, ControlType, RenderTarget } from "unframer"
import { motion } from "unframer"

// /:https://framerusercontent.com/modules/Qc8yuHkQmGO0kFiSWbkX/rVmMAFttOHuuiwSg6KjZ/House.js
var Component
var IconInner
var Icon2 = (React3) => {
  if (!Component) {
    Component = /* @__PURE__ */ new Map([
      [
        "bold",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M222.14,105.85l-80-80a20,20,0,0,0-28.28,0l-80,80A19.86,19.86,0,0,0,28,120v96a12,12,0,0,0,12,12h64a12,12,0,0,0,12-12V164h24v52a12,12,0,0,0,12,12h64a12,12,0,0,0,12-12V120A19.86,19.86,0,0,0,222.14,105.85ZM204,204H164V152a12,12,0,0,0-12-12H104a12,12,0,0,0-12,12v52H52V121.65l76-76,76,76Z",
          })
        ),
      ],
      [
        "duotone",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M216,120v96H152V152H104v64H40V120a8,8,0,0,1,2.34-5.66l80-80a8,8,0,0,1,11.32,0l80,80A8,8,0,0,1,216,120Z",
            opacity: "0.2",
          }),
          /* @__PURE__ */ React3.createElement("path", {
            d: "M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z",
          })
        ),
      ],
      [
        "fill",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M224,120v96a8,8,0,0,1-8,8H160a8,8,0,0,1-8-8V164a4,4,0,0,0-4-4H108a4,4,0,0,0-4,4v52a8,8,0,0,1-8,8H40a8,8,0,0,1-8-8V120a16,16,0,0,1,4.69-11.31l80-80a16,16,0,0,1,22.62,0l80,80A16,16,0,0,1,224,120Z",
          })
        ),
      ],
      [
        "light",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M217.9,110.1l-80-80a14,14,0,0,0-19.8,0l-80,80A13.92,13.92,0,0,0,34,120v96a6,6,0,0,0,6,6h64a6,6,0,0,0,6-6V158h36v58a6,6,0,0,0,6,6h64a6,6,0,0,0,6-6V120A13.92,13.92,0,0,0,217.9,110.1ZM210,210H158V152a6,6,0,0,0-6-6H104a6,6,0,0,0-6,6v58H46V120a2,2,0,0,1,.58-1.42l80-80a2,2,0,0,1,2.84,0l80,80A2,2,0,0,1,210,120Z",
          })
        ),
      ],
      [
        "regular",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M219.31,108.68l-80-80a16,16,0,0,0-22.62,0l-80,80A15.87,15.87,0,0,0,32,120v96a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V160h32v56a8,8,0,0,0,8,8h64a8,8,0,0,0,8-8V120A15.87,15.87,0,0,0,219.31,108.68ZM208,208H160V152a8,8,0,0,0-8-8H104a8,8,0,0,0-8,8v56H48V120l80-80,80,80Z",
          })
        ),
      ],
      [
        "thin",
        /* @__PURE__ */ React3.createElement(
          React3.Fragment,
          null,
          /* @__PURE__ */ React3.createElement("path", {
            d: "M216.49,111.51l-80-80a12,12,0,0,0-17,0l-80,80A12,12,0,0,0,36,120v96a4,4,0,0,0,4,4h64a4,4,0,0,0,4-4V156h40v60a4,4,0,0,0,4,4h64a4,4,0,0,0,4-4V120A12,12,0,0,0,216.49,111.51ZM212,212H156V152a4,4,0,0,0-4-4H104a4,4,0,0,0-4,4v60H44V120a4,4,0,0,1,1.17-2.83l80-80a4,4,0,0,1,5.66,0l80,80A4,4,0,0,1,212,120Z",
          })
        ),
      ],
    ])
    IconInner = React3.forwardRef((props, ref) =>
      /* @__PURE__ */ React3.createElement(
        "g",
        {
          ref,
          ...props,
        },
        Component.get(props.weight)
      )
    )
  }
  return IconInner
}
var House_default = Icon2

// /:https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js
var iconKeys = [
  "Acorn",
  "AddressBook",
  "AddressBookTabs",
  "AirTrafficControl",
  "Airplane",
  "AirplaneInFlight",
  "AirplaneLanding",
  "AirplaneTakeoff",
  "AirplaneTaxiing",
  "AirplaneTilt",
  "Airplay",
  "Alarm",
  "Alien",
  "AlignBottom",
  "AlignBottomSimple",
  "AlignCenterVertical",
  "AlignLeft",
  "AlignLeftSimple",
  "AlignRight",
  "AlignRightSimple",
  "AlignTop",
  "AlignTopSimple",
  "AmazonLogo",
  "Ambulance",
  "Anchor",
  "AnchorSimple",
  "AndroidLogo",
  "Angle",
  "AngularLogo",
  "Aperture",
  "AppStoreLogo",
  "AppWindow",
  "AppleLogo",
  "ApplePodcastsLogo",
  "ApproximateEquals",
  "Archive",
  "ArchiveBox",
  "ArchiveTray",
  "Armchair",
  "ArrowArcLeft",
  "ArrowArcRight",
  "ArrowBendDownLeft",
  "ArrowBendDownRight",
  "ArrowBendLeftDown",
  "ArrowBendLeftUp",
  "ArrowBendRightDown",
  "ArrowBendRightUp",
  "ArrowBendUpLeft",
  "ArrowBendUpRight",
  "ArrowCircleDown",
  "ArrowCircleDownLeft",
  "ArrowCircleDownRight",
  "ArrowCircleLeft",
  "ArrowCircleRight",
  "ArrowCircleUp",
  "ArrowCircleUpLeft",
  "ArrowCircleUpRight",
  "ArrowClockwise",
  "ArrowDown",
  "ArrowDownLeft",
  "ArrowDownRight",
  "ArrowElbowDownLeft",
  "ArrowElbowDownRight",
  "ArrowElbowLeft",
  "ArrowElbowLeftDown",
  "ArrowElbowLeftUp",
  "ArrowElbowRight",
  "ArrowElbowRightDown",
  "ArrowElbowRightUp",
  "ArrowElbowUpLeft",
  "ArrowElbowUpRight",
  "ArrowFatDown",
  "ArrowFatLeft",
  "ArrowFatLineDown",
  "ArrowFatLineLeft",
  "ArrowFatLineRight",
  "ArrowFatLineUp",
  "ArrowFatLinesDown",
  "ArrowFatLinesLeft",
  "ArrowFatLinesRight",
  "ArrowFatLinesUp",
  "ArrowFatRight",
  "ArrowFatUp",
  "ArrowLeft",
  "ArrowLineDown",
  "ArrowLineDownLeft",
  "ArrowLineDownRight",
  "ArrowLineLeft",
  "ArrowLineRight",
  "ArrowLineUp",
  "ArrowLineUpLeft",
  "ArrowLineUpRight",
  "ArrowRight",
  "ArrowSquareDown",
  "ArrowSquareDownLeft",
  "ArrowSquareDownRight",
  "ArrowSquareIn",
  "ArrowSquareLeft",
  "ArrowSquareOut",
  "ArrowSquareRight",
  "ArrowSquareUp",
  "ArrowSquareUpLeft",
  "ArrowSquareUpRight",
  "ArrowUDownLeft",
  "ArrowUDownRight",
  "ArrowULeftDown",
  "ArrowULeftUp",
  "ArrowURightDown",
  "ArrowURightUp",
  "ArrowUUpLeft",
  "ArrowUUpRight",
  "ArrowUp",
  "ArrowUpLeft",
  "ArrowUpRight",
  "ArrowsClockwise",
  "ArrowsDownUp",
  "ArrowsHorizontal",
  "ArrowsIn",
  "ArrowsInCardinal",
  "ArrowsInLineVertical",
  "ArrowsInSimple",
  "ArrowsLeftRight",
  "ArrowsMerge",
  "ArrowsOut",
  "ArrowsOutCardinal",
  "ArrowsOutSimple",
  "ArrowsSplit",
  "ArrowsVertical",
  "Article",
  "ArticleMedium",
  "ArticleNyTimes",
  "Asclepius",
  "Asterisk",
  "AsteriskSimple",
  "At",
  "Atom",
  "Avocado",
  "Axe",
  "Baby",
  "BabyCarriage",
  "Backpack",
  "Backspace",
  "Bag",
  "BagSimple",
  "Balloon",
  "Bandaids",
  "Bank",
  "Barbell",
  "Barcode",
  "Barn",
  "Barricade",
  "Baseball",
  "BaseballCap",
  "BaseballHelmet",
  "Basket",
  "Basketball",
  "Bathtub",
  "BatteryCharging",
  "BatteryEmpty",
  "BatteryFull",
  "BatteryHigh",
  "BatteryLow",
  "BatteryMedium",
  "BatteryPlus",
  "BatteryPlusVertical",
  "BatteryVerticalEmpty",
  "BatteryVerticalFull",
  "BatteryVerticalHigh",
  "BatteryVerticalLow",
  "BatteryWarning",
  "BeachBall",
  "Beanie",
  "Bed",
  "BeerBottle",
  "BeerStein",
  "BehanceLogo",
  "Bell",
  "BellRinging",
  "BellSimple",
  "BellSimpleRinging",
  "BellSimpleSlash",
  "BellSimpleZ",
  "BellSlash",
  "BellZ",
  "Belt",
  "BezierCurve",
  "Bicycle",
  "Binary",
  "Binoculars",
  "Biohazard",
  "Bird",
  "Blueprint",
  "Bluetooth",
  "BluetoothConnected",
  "BluetoothSlash",
  "BluetoothX",
  "Boat",
  "Bomb",
  "Bone",
  "Book",
  "BookBookmark",
  "BookOpen",
  "BookOpenText",
  "BookOpenUser",
  "BookUser",
  "Bookmark",
  "BookmarkSimple",
  "Bookmarks",
  "BookmarksSimple",
  "Books",
  "Boot",
  "Boules",
  "BoundingBox",
  "BowlFood",
  "BowlSteam",
  "BowlingBall",
  "BoxArrowDown",
  "BoxArrowUp",
  "BoxingGlove",
  "BracketsAngle",
  "BracketsCurly",
  "BracketsRound",
  "BracketsSquare",
  "Brain",
  "Brandy",
  "Bread",
  "Bridge",
  "Briefcase",
  "BriefcaseMetal",
  "Broadcast",
  "Broom",
  "Browser",
  "Browsers",
  "Bug",
  "BugBeetle",
  "BugDroid",
  "Building",
  "BuildingApartment",
  "BuildingOffice",
  "Buildings",
  "Bulldozer",
  "Bus",
  "Butterfly",
  "CableCar",
  "Cactus",
  "Cake",
  "Calculator",
  "Calendar",
  "CalendarBlank",
  "CalendarCheck",
  "CalendarDot",
  "CalendarDots",
  "CalendarHeart",
  "CalendarMinus",
  "CalendarPlus",
  "CalendarSlash",
  "CalendarStar",
  "CalendarX",
  "CallBell",
  "Camera",
  "CameraPlus",
  "CameraRotate",
  "CameraSlash",
  "Campfire",
  "Car",
  "CarBattery",
  "CarProfile",
  "CarSimple",
  "Cardholder",
  "Cards",
  "CardsThree",
  "CaretCircleDoubleUp",
  "CaretCircleDown",
  "CaretCircleLeft",
  "CaretCircleRight",
  "CaretCircleUp",
  "CaretCircleUpDown",
  "CaretDoubleDown",
  "CaretDoubleLeft",
  "CaretDoubleRight",
  "CaretDoubleUp",
  "CaretDown",
  "CaretLeft",
  "CaretLineDown",
  "CaretLineLeft",
  "CaretLineRight",
  "CaretLineUp",
  "CaretRight",
  "CaretUp",
  "CaretUpDown",
  "Carrot",
  "CashRegister",
  "CassetteTape",
  "CastleTurret",
  "Cat",
  "CellSignalFull",
  "CellSignalHigh",
  "CellSignalLow",
  "CellSignalMedium",
  "CellSignalNone",
  "CellSignalSlash",
  "CellSignalX",
  "CellTower",
  "Certificate",
  "Chair",
  "Chalkboard",
  "ChalkboardSimple",
  "ChalkboardTeacher",
  "Champagne",
  "ChargingStation",
  "ChartBar",
  "ChartBarHorizontal",
  "ChartDonut",
  "ChartLine",
  "ChartLineDown",
  "ChartLineUp",
  "ChartPie",
  "ChartPieSlice",
  "ChartPolar",
  "ChartScatter",
  "Chat",
  "ChatCentered",
  "ChatCenteredDots",
  "ChatCenteredSlash",
  "ChatCenteredText",
  "ChatCircle",
  "ChatCircleDots",
  "ChatCircleSlash",
  "ChatCircleText",
  "ChatDots",
  "ChatSlash",
  "ChatTeardrop",
  "ChatTeardropDots",
  "ChatTeardropSlash",
  "ChatTeardropText",
  "ChatText",
  "Chats",
  "ChatsCircle",
  "ChatsTeardrop",
  "Check",
  "CheckCircle",
  "CheckFat",
  "CheckSquare",
  "CheckSquareOffset",
  "Checkerboard",
  "Checks",
  "Cheers",
  "Cheese",
  "ChefHat",
  "Cherries",
  "Church",
  "Cigarette",
  "CigaretteSlash",
  "Circle",
  "CircleDashed",
  "CircleHalf",
  "CircleHalfTilt",
  "CircleNotch",
  "CirclesFour",
  "CirclesThree",
  "CirclesThreePlus",
  "Circuitry",
  "City",
  "Clipboard",
  "ClipboardText",
  "Clock",
  "ClockAfternoon",
  "ClockClockwise",
  "ClockCountdown",
  "ClockUser",
  "ClosedCaptioning",
  "Cloud",
  "CloudArrowDown",
  "CloudArrowUp",
  "CloudCheck",
  "CloudFog",
  "CloudLightning",
  "CloudMoon",
  "CloudRain",
  "CloudSlash",
  "CloudSnow",
  "CloudSun",
  "CloudWarning",
  "CloudX",
  "Clover",
  "Club",
  "CoatHanger",
  "CodaLogo",
  "Code",
  "CodeBlock",
  "CodeSimple",
  "CodepenLogo",
  "CodesandboxLogo",
  "Coffee",
  "CoffeeBean",
  "Coin",
  "CoinVertical",
  "Coins",
  "Columns",
  "ColumnsPlusLeft",
  "ColumnsPlusRight",
  "Command",
  "Compass",
  "CompassRose",
  "CompassTool",
  "ComputerTower",
  "Confetti",
  "ContactlessPayment",
  "Control",
  "Cookie",
  "CookingPot",
  "Copy",
  "CopySimple",
  "Copyleft",
  "Copyright",
  "CornersIn",
  "CornersOut",
  "Couch",
  "CourtBasketball",
  "Cow",
  "CowboyHat",
  "Cpu",
  "Crane",
  "CraneTower",
  "CreditCard",
  "Cricket",
  "Crop",
  "Cross",
  "Crosshair",
  "CrosshairSimple",
  "Crown",
  "CrownCross",
  "CrownSimple",
  "Cube",
  "CubeFocus",
  "CubeTransparent",
  "CurrencyBtc",
  "CurrencyCircleDollar",
  "CurrencyCny",
  "CurrencyDollar",
  "CurrencyDollarSimple",
  "CurrencyEth",
  "CurrencyEur",
  "CurrencyGbp",
  "CurrencyInr",
  "CurrencyJpy",
  "CurrencyKrw",
  "CurrencyKzt",
  "CurrencyNgn",
  "CurrencyRub",
  "Cursor",
  "CursorClick",
  "CursorText",
  "Cylinder",
  "Database",
  "Desk",
  "Desktop",
  "DesktopTower",
  "Detective",
  "DevToLogo",
  "DeviceMobile",
  "DeviceMobileCamera",
  "DeviceMobileSlash",
  "DeviceMobileSpeaker",
  "DeviceRotate",
  "DeviceTablet",
  "DeviceTabletCamera",
  "DeviceTabletSpeaker",
  "Devices",
  "Diamond",
  "DiamondsFour",
  "DiceFive",
  "DiceFour",
  "DiceOne",
  "DiceSix",
  "DiceThree",
  "DiceTwo",
  "Disc",
  "DiscoBall",
  "DiscordLogo",
  "Divide",
  "Dna",
  "Dog",
  "Door",
  "DoorOpen",
  "Dot",
  "DotOutline",
  "DotsNine",
  "DotsSix",
  "DotsSixVertical",
  "DotsThree",
  "DotsThreeCircle",
  "DotsThreeOutline",
  "DotsThreeVertical",
  "Download",
  "DownloadSimple",
  "Dress",
  "Dresser",
  "DribbbleLogo",
  "Drone",
  "Drop",
  "DropHalf",
  "DropHalfBottom",
  "DropSimple",
  "DropSlash",
  "DropboxLogo",
  "Ear",
  "EarSlash",
  "Egg",
  "EggCrack",
  "Eject",
  "EjectSimple",
  "Elevator",
  "Empty",
  "Engine",
  "Envelope",
  "EnvelopeOpen",
  "EnvelopeSimple",
  "EnvelopeSimpleOpen",
  "Equalizer",
  "Equals",
  "Eraser",
  "EscalatorDown",
  "EscalatorUp",
  "Exam",
  "ExclamationMark",
  "Exclude",
  "ExcludeSquare",
  "Export",
  "Eye",
  "EyeClosed",
  "EyeSlash",
  "Eyedropper",
  "EyedropperSample",
  "Eyeglasses",
  "Eyes",
  "FaceMask",
  "FacebookLogo",
  "Factory",
  "Faders",
  "FadersHorizontal",
  "FalloutShelter",
  "Fan",
  "Farm",
  "FastForward",
  "FastForwardCircle",
  "Feather",
  "FediverseLogo",
  "FigmaLogo",
  "File",
  "FileArchive",
  "FileArrowDown",
  "FileArrowUp",
  "FileAudio",
  "FileC",
  "FileCloud",
  "FileCode",
  "FileCpp",
  "FileCss",
  "FileCsv",
  "FileDashed",
  "FileDoc",
  "FileHtml",
  "FileImage",
  "FileIni",
  "FileJpg",
  "FileJs",
  "FileJsx",
  "FileLock",
  "FileMagnifyingGlass",
  "FileMd",
  "FileMinus",
  "FilePdf",
  "FilePlus",
  "FilePng",
  "FilePpt",
  "FilePy",
  "FileRs",
  "FileSql",
  "FileSvg",
  "FileText",
  "FileTs",
  "FileTsx",
  "FileTxt",
  "FileVideo",
  "FileVue",
  "FileX",
  "FileXls",
  "FileZip",
  "Files",
  "FilmReel",
  "FilmScript",
  "FilmSlate",
  "FilmStrip",
  "Fingerprint",
  "FingerprintSimple",
  "FinnTheHuman",
  "Fire",
  "FireExtinguisher",
  "FireSimple",
  "FireTruck",
  "FirstAid",
  "FirstAidKit",
  "Fish",
  "FishSimple",
  "Flag",
  "FlagBanner",
  "FlagBannerFold",
  "FlagCheckered",
  "FlagPennant",
  "Flame",
  "Flashlight",
  "Flask",
  "FlipHorizontal",
  "FlipVertical",
  "FloppyDisk",
  "FloppyDiskBack",
  "FlowArrow",
  "Flower",
  "FlowerLotus",
  "FlowerTulip",
  "FlyingSaucer",
  "Folder",
  "FolderDashed",
  "FolderLock",
  "FolderMinus",
  "FolderNotch",
  "FolderNotchMinus",
  "FolderNotchOpen",
  "FolderNotchPlus",
  "FolderOpen",
  "FolderPlus",
  "FolderSimple",
  "FolderSimpleDashed",
  "FolderSimpleLock",
  "FolderSimpleMinus",
  "FolderSimplePlus",
  "FolderSimpleStar",
  "FolderSimpleUser",
  "FolderStar",
  "FolderUser",
  "Folders",
  "Football",
  "FootballHelmet",
  "Footprints",
  "ForkKnife",
  "FourK",
  "FrameCorners",
  "FramerLogo",
  "Function",
  "Funnel",
  "FunnelSimple",
  "FunnelSimpleX",
  "FunnelX",
  "GameController",
  "Garage",
  "GasCan",
  "GasPump",
  "Gauge",
  "Gavel",
  "Gear",
  "GearFine",
  "GearSix",
  "GenderFemale",
  "GenderIntersex",
  "GenderMale",
  "GenderNeuter",
  "GenderNonbinary",
  "GenderTransgender",
  "Ghost",
  "Gif",
  "Gift",
  "GitBranch",
  "GitCommit",
  "GitDiff",
  "GitFork",
  "GitMerge",
  "GitPullRequest",
  "GithubLogo",
  "GitlabLogo",
  "GitlabLogoSimple",
  "Globe",
  "GlobeHemisphereEast",
  "GlobeHemisphereWest",
  "GlobeSimple",
  "GlobeSimpleX",
  "GlobeStand",
  "GlobeX",
  "Goggles",
  "Golf",
  "GoodreadsLogo",
  "GoogleCardboardLogo",
  "GoogleChromeLogo",
  "GoogleDriveLogo",
  "GoogleLogo",
  "GooglePhotosLogo",
  "GooglePlayLogo",
  "GooglePodcastsLogo",
  "Gps",
  "GpsFix",
  "GpsSlash",
  "Gradient",
  "GraduationCap",
  "Grains",
  "GrainsSlash",
  "Graph",
  "GraphicsCard",
  "GreaterThan",
  "GreaterThanOrEqual",
  "GridFour",
  "GridNine",
  "Guitar",
  "HairDryer",
  "Hamburger",
  "Hammer",
  "Hand",
  "HandArrowDown",
  "HandArrowUp",
  "HandCoins",
  "HandDeposit",
  "HandEye",
  "HandFist",
  "HandGrabbing",
  "HandHeart",
  "HandPalm",
  "HandPeace",
  "HandPointing",
  "HandSoap",
  "HandSwipeLeft",
  "HandSwipeRight",
  "HandTap",
  "HandWaving",
  "HandWithdraw",
  "Handbag",
  "HandbagSimple",
  "HandsClapping",
  "HandsPraying",
  "Handshake",
  "HardDrive",
  "HardDrives",
  "HardHat",
  "Hash",
  "HashStraight",
  "HeadCircuit",
  "Headlights",
  "Headphones",
  "Headset",
  "Heart",
  "HeartBreak",
  "HeartHalf",
  "HeartStraight",
  "HeartStraightBreak",
  "Heartbeat",
  "Hexagon",
  "HighDefinition",
  "HighHeel",
  "Highlighter",
  "HighlighterCircle",
  "Hockey",
  "Hoodie",
  "Horse",
  "Hospital",
  "Hourglass",
  "HourglassHigh",
  "HourglassLow",
  "HourglassMedium",
  "HourglassSimple",
  "HourglassSimpleHigh",
  "HourglassSimpleLow",
  "House",
  "HouseLine",
  "HouseSimple",
  "Hurricane",
  "IceCream",
  "IdentificationBadge",
  "IdentificationCard",
  "Image",
  "ImageBroken",
  "ImageSquare",
  "Images",
  "ImagesSquare",
  "Infinity",
  "Info",
  "InstagramLogo",
  "Intersect",
  "IntersectSquare",
  "IntersectThree",
  "Intersection",
  "Invoice",
  "Island",
  "Jar",
  "JarLabel",
  "Jeep",
  "Joystick",
  "Kanban",
  "Key",
  "KeyReturn",
  "Keyboard",
  "Keyhole",
  "Knife",
  "Ladder",
  "LadderSimple",
  "Lamp",
  "LampPendant",
  "Laptop",
  "Lasso",
  "LastfmLogo",
  "Layout",
  "Leaf",
  "Lectern",
  "Lego",
  "LegoSmiley",
  "LessThan",
  "LessThanOrEqual",
  "LetterCircleH",
  "LetterCircleP",
  "LetterCircleV",
  "Lifebuoy",
  "Lightbulb",
  "LightbulbFilament",
  "Lighthouse",
  "Lightning",
  "LightningA",
  "LightningSlash",
  "LineSegment",
  "LineSegments",
  "LineVertical",
  "Link",
  "LinkBreak",
  "LinkSimple",
  "LinkSimpleBreak",
  "LinkSimpleHorizontal",
  "LinkedinLogo",
  "LinktreeLogo",
  "LinuxLogo",
  "List",
  "ListBullets",
  "ListChecks",
  "ListDashes",
  "ListHeart",
  "ListMagnifyingGlass",
  "ListNumbers",
  "ListPlus",
  "ListStar",
  "Lock",
  "LockKey",
  "LockKeyOpen",
  "LockLaminated",
  "LockLaminatedOpen",
  "LockOpen",
  "LockSimple",
  "LockSimpleOpen",
  "Lockers",
  "Log",
  "MagicWand",
  "Magnet",
  "MagnetStraight",
  "MagnifyingGlass",
  "MagnifyingGlassMinus",
  "MagnifyingGlassPlus",
  "Mailbox",
  "MapPin",
  "MapPinArea",
  "MapPinLine",
  "MapPinPlus",
  "MapPinSimple",
  "MapPinSimpleArea",
  "MapPinSimpleLine",
  "MapTrifold",
  "MarkdownLogo",
  "MarkerCircle",
  "Martini",
  "MaskHappy",
  "MaskSad",
  "MastodonLogo",
  "MathOperations",
  "MatrixLogo",
  "Medal",
  "MedalMilitary",
  "MediumLogo",
  "Megaphone",
  "MegaphoneSimple",
  "MemberOf",
  "Memory",
  "MessengerLogo",
  "MetaLogo",
  "Meteor",
  "Metronome",
  "Microphone",
  "MicrophoneSlash",
  "MicrophoneStage",
  "Microscope",
  "MicrosoftExcelLogo",
  "MicrosoftOutlookLogo",
  "MicrosoftTeamsLogo",
  "MicrosoftWordLogo",
  "Minus",
  "MinusCircle",
  "MinusSquare",
  "Money",
  "MoneyWavy",
  "Monitor",
  "MonitorArrowUp",
  "MonitorPlay",
  "Moon",
  "MoonStars",
  "Moped",
  "MopedFront",
  "Mosque",
  "Motorcycle",
  "Mountains",
  "Mouse",
  "MouseLeftClick",
  "MouseMiddleClick",
  "MouseRightClick",
  "MouseScroll",
  "MouseSimple",
  "MusicNote",
  "MusicNoteSimple",
  "MusicNotes",
  "MusicNotesMinus",
  "MusicNotesPlus",
  "MusicNotesSimple",
  "NavigationArrow",
  "Needle",
  "Network",
  "NetworkSlash",
  "NetworkX",
  "Newspaper",
  "NewspaperClipping",
  "NotEquals",
  "NotMemberOf",
  "NotSubsetOf",
  "NotSupersetOf",
  "Notches",
  "Note",
  "NoteBlank",
  "NotePencil",
  "Notebook",
  "Notepad",
  "Notification",
  "NotionLogo",
  "NuclearPlant",
  "NumberCircleEight",
  "NumberCircleFive",
  "NumberCircleFour",
  "NumberCircleNine",
  "NumberCircleOne",
  "NumberCircleSeven",
  "NumberCircleSix",
  "NumberCircleThree",
  "NumberCircleTwo",
  "NumberCircleZero",
  "NumberEight",
  "NumberFive",
  "NumberFour",
  "NumberNine",
  "NumberOne",
  "NumberSeven",
  "NumberSix",
  "NumberSquareEight",
  "NumberSquareFive",
  "NumberSquareFour",
  "NumberSquareNine",
  "NumberSquareOne",
  "NumberSquareSeven",
  "NumberSquareSix",
  "NumberSquareThree",
  "NumberSquareTwo",
  "NumberSquareZero",
  "NumberThree",
  "NumberTwo",
  "NumberZero",
  "Numpad",
  "Nut",
  "NyTimesLogo",
  "Octagon",
  "OfficeChair",
  "Onigiri",
  "OpenAiLogo",
  "Option",
  "Orange",
  "OrangeSlice",
  "Oven",
  "Package",
  "PaintBrush",
  "PaintBrushBroad",
  "PaintBrushHousehold",
  "PaintBucket",
  "PaintRoller",
  "Palette",
  "Panorama",
  "Pants",
  "PaperPlane",
  "PaperPlaneRight",
  "PaperPlaneTilt",
  "Paperclip",
  "PaperclipHorizontal",
  "Parachute",
  "Paragraph",
  "Parallelogram",
  "Park",
  "Password",
  "Path",
  "PatreonLogo",
  "Pause",
  "PauseCircle",
  "PawPrint",
  "PaypalLogo",
  "Peace",
  "Pen",
  "PenNib",
  "PenNibStraight",
  "Pencil",
  "PencilCircle",
  "PencilLine",
  "PencilRuler",
  "PencilSimple",
  "PencilSimpleLine",
  "PencilSimpleSlash",
  "PencilSlash",
  "Pentagon",
  "Pentagram",
  "Pepper",
  "Percent",
  "Person",
  "PersonArmsSpread",
  "PersonSimple",
  "PersonSimpleBike",
  "PersonSimpleCircle",
  "PersonSimpleHike",
  "PersonSimpleRun",
  "PersonSimpleSki",
  "PersonSimpleSwim",
  "PersonSimpleTaiChi",
  "PersonSimpleThrow",
  "PersonSimpleWalk",
  "Perspective",
  "Phone",
  "PhoneCall",
  "PhoneDisconnect",
  "PhoneIncoming",
  "PhoneList",
  "PhoneOutgoing",
  "PhonePause",
  "PhonePlus",
  "PhoneSlash",
  "PhoneTransfer",
  "PhoneX",
  "PhosphorLogo",
  "Pi",
  "PianoKeys",
  "PicnicTable",
  "PictureInPicture",
  "PiggyBank",
  "Pill",
  "PingPong",
  "PintGlass",
  "PinterestLogo",
  "Pinwheel",
  "Pipe",
  "PipeWrench",
  "PixLogo",
  "Pizza",
  "Placeholder",
  "Planet",
  "Plant",
  "Play",
  "PlayCircle",
  "PlayPause",
  "Playlist",
  "Plug",
  "PlugCharging",
  "Plugs",
  "PlugsConnected",
  "Plus",
  "PlusCircle",
  "PlusMinus",
  "PlusSquare",
  "PokerChip",
  "PoliceCar",
  "Polygon",
  "Popcorn",
  "Popsicle",
  "PottedPlant",
  "Power",
  "Prescription",
  "Presentation",
  "PresentationChart",
  "Printer",
  "Prohibit",
  "ProhibitInset",
  "ProjectorScreen",
  "ProjectorScreenChart",
  "Pulse",
  "PushPin",
  "PushPinSimple",
  "PushPinSimpleSlash",
  "PushPinSlash",
  "PuzzlePiece",
  "QrCode",
  "Question",
  "QuestionMark",
  "Queue",
  "Quotes",
  "Rabbit",
  "Racquet",
  "Radical",
  "Radio",
  "RadioButton",
  "Radioactive",
  "Rainbow",
  "RainbowCloud",
  "Ranking",
  "ReadCvLogo",
  "Receipt",
  "ReceiptX",
  "Record",
  "Rectangle",
  "RectangleDashed",
  "Recycle",
  "RedditLogo",
  "Repeat",
  "RepeatOnce",
  "ReplitLogo",
  "Resize",
  "Rewind",
  "RewindCircle",
  "RoadHorizon",
  "Robot",
  "Rocket",
  "RocketLaunch",
  "Rows",
  "RowsPlusBottom",
  "RowsPlusTop",
  "Rss",
  "RssSimple",
  "Rug",
  "Ruler",
  "Sailboat",
  "Scales",
  "Scan",
  "ScanSmiley",
  "Scissors",
  "Scooter",
  "Screencast",
  "Screwdriver",
  "Scribble",
  "ScribbleLoop",
  "Scroll",
  "Seal",
  "SealCheck",
  "SealPercent",
  "SealQuestion",
  "SealWarning",
  "Seat",
  "Seatbelt",
  "SecurityCamera",
  "Selection",
  "SelectionAll",
  "SelectionBackground",
  "SelectionForeground",
  "SelectionInverse",
  "SelectionPlus",
  "SelectionSlash",
  "Shapes",
  "Share",
  "ShareFat",
  "ShareNetwork",
  "Shield",
  "ShieldCheck",
  "ShieldCheckered",
  "ShieldChevron",
  "ShieldPlus",
  "ShieldSlash",
  "ShieldStar",
  "ShieldWarning",
  "ShippingContainer",
  "ShirtFolded",
  "ShootingStar",
  "ShoppingBag",
  "ShoppingBagOpen",
  "ShoppingCart",
  "ShoppingCartSimple",
  "Shovel",
  "Shower",
  "Shrimp",
  "Shuffle",
  "ShuffleAngular",
  "ShuffleSimple",
  "Sidebar",
  "SidebarSimple",
  "Sigma",
  "SignIn",
  "SignOut",
  "Signature",
  "Signpost",
  "SimCard",
  "Siren",
  "SketchLogo",
  "SkipBack",
  "SkipBackCircle",
  "SkipForward",
  "SkipForwardCircle",
  "Skull",
  "SkypeLogo",
  "SlackLogo",
  "Sliders",
  "SlidersHorizontal",
  "Slideshow",
  "Smiley",
  "SmileyAngry",
  "SmileyBlank",
  "SmileyMeh",
  "SmileyMelting",
  "SmileyNervous",
  "SmileySad",
  "SmileySticker",
  "SmileyWink",
  "SmileyXEyes",
  "SnapchatLogo",
  "Sneaker",
  "SneakerMove",
  "Snowflake",
  "SoccerBall",
  "Sock",
  "SolarPanel",
  "SolarRoof",
  "SortAscending",
  "SortDescending",
  "SoundcloudLogo",
  "Spade",
  "Sparkle",
  "SpeakerHifi",
  "SpeakerHigh",
  "SpeakerLow",
  "SpeakerNone",
  "SpeakerSimpleHigh",
  "SpeakerSimpleLow",
  "SpeakerSimpleNone",
  "SpeakerSimpleSlash",
  "SpeakerSimpleX",
  "SpeakerSlash",
  "SpeakerX",
  "Speedometer",
  "Sphere",
  "Spinner",
  "SpinnerBall",
  "SpinnerGap",
  "Spiral",
  "SplitHorizontal",
  "SplitVertical",
  "SpotifyLogo",
  "SprayBottle",
  "Square",
  "SquareHalf",
  "SquareHalfBottom",
  "SquareLogo",
  "SquareSplitVertical",
  "SquaresFour",
  "Stack",
  "StackMinus",
  "StackOverflowLogo",
  "StackPlus",
  "StackSimple",
  "Stairs",
  "Stamp",
  "StandardDefinition",
  "Star",
  "StarAndCrescent",
  "StarFour",
  "StarHalf",
  "StarOfDavid",
  "SteamLogo",
  "SteeringWheel",
  "Steps",
  "Stethoscope",
  "Sticker",
  "Stool",
  "Stop",
  "StopCircle",
  "Storefront",
  "Strategy",
  "StripeLogo",
  "Student",
  "SubsetOf",
  "SubsetProperOf",
  "Subtitles",
  "SubtitlesSlash",
  "Subtract",
  "SubtractSquare",
  "Subway",
  "Suitcase",
  "SuitcaseRolling",
  "SuitcaseSimple",
  "Sun",
  "SunDim",
  "SunHorizon",
  "Sunglasses",
  "SupersetOf",
  "SupersetProperOf",
  "Swap",
  "Swatches",
  "SwimmingPool",
  "Sword",
  "Synagogue",
  "Syringe",
  "TShirt",
  "Table",
  "Tabs",
  "Tag",
  "TagChevron",
  "TagSimple",
  "Target",
  "Taxi",
  "TeaBag",
  "TelegramLogo",
  "Television",
  "TelevisionSimple",
  "TennisBall",
  "Tent",
  "Terminal",
  "TerminalWindow",
  "TestTube",
  "TextAUnderline",
  "TextAa",
  "TextAlignCenter",
  "TextAlignJustify",
  "TextAlignLeft",
  "TextAlignRight",
  "TextB",
  "TextColumns",
  "TextH",
  "TextHFive",
  "TextHFour",
  "TextHOne",
  "TextHSix",
  "TextHThree",
  "TextHTwo",
  "TextIndent",
  "TextItalic",
  "TextOutdent",
  "TextStrikethrough",
  "TextSubscript",
  "TextSuperscript",
  "TextT",
  "TextTSlash",
  "TextUnderline",
  "Textbox",
  "Thermometer",
  "ThermometerCold",
  "ThermometerHot",
  "ThermometerSimple",
  "ThreadsLogo",
  "ThreeD",
  "ThumbsDown",
  "ThumbsUp",
  "Ticket",
  "TidalLogo",
  "TiktokLogo",
  "Tilde",
  "Timer",
  "TipJar",
  "Tipi",
  "Tire",
  "ToggleLeft",
  "ToggleRight",
  "Toilet",
  "ToiletPaper",
  "Toolbox",
  "Tooth",
  "Tornado",
  "Tote",
  "ToteSimple",
  "Towel",
  "Tractor",
  "Trademark",
  "TrademarkRegistered",
  "TrafficCone",
  "TrafficSign",
  "TrafficSignal",
  "Train",
  "TrainRegional",
  "TrainSimple",
  "Tram",
  "Translate",
  "Trash",
  "TrashSimple",
  "Tray",
  "TrayArrowDown",
  "TrayArrowUp",
  "TreasureChest",
  "Tree",
  "TreeEvergreen",
  "TreePalm",
  "TreeStructure",
  "TreeView",
  "TrendDown",
  "TrendUp",
  "Triangle",
  "TriangleDashed",
  "Trolley",
  "TrolleySuitcase",
  "Trophy",
  "Truck",
  "TruckTrailer",
  "TumblrLogo",
  "TwitchLogo",
  "TwitterLogo",
  "Umbrella",
  "UmbrellaSimple",
  "Union",
  "Unite",
  "UniteSquare",
  "Upload",
  "UploadSimple",
  "Usb",
  "User",
  "UserCheck",
  "UserCircle",
  "UserCircleCheck",
  "UserCircleDashed",
  "UserCircleGear",
  "UserCircleMinus",
  "UserCirclePlus",
  "UserFocus",
  "UserGear",
  "UserList",
  "UserMinus",
  "UserPlus",
  "UserRectangle",
  "UserSound",
  "UserSquare",
  "UserSwitch",
  "Users",
  "UsersFour",
  "UsersThree",
  "Van",
  "Vault",
  "VectorThree",
  "VectorTwo",
  "Vibrate",
  "Video",
  "VideoCamera",
  "VideoCameraSlash",
  "VideoConference",
  "Vignette",
  "VinylRecord",
  "VirtualReality",
  "Virus",
  "Visor",
  "Voicemail",
  "Volleyball",
  "Wall",
  "Wallet",
  "Warehouse",
  "Warning",
  "WarningCircle",
  "WarningDiamond",
  "WarningOctagon",
  "WashingMachine",
  "Watch",
  "WaveSawtooth",
  "WaveSine",
  "WaveSquare",
  "WaveTriangle",
  "Waveform",
  "WaveformSlash",
  "Waves",
  "Webcam",
  "WebcamSlash",
  "WebhooksLogo",
  "WechatLogo",
  "WhatsappLogo",
  "Wheelchair",
  "WheelchairMotion",
  "WifiHigh",
  "WifiLow",
  "WifiMedium",
  "WifiNone",
  "WifiSlash",
  "WifiX",
  "Wind",
  "Windmill",
  "WindowsLogo",
  "Wine",
  "Wrench",
  "X",
  "XCircle",
  "XLogo",
  "XSquare",
  "Yarn",
  "YinYang",
  "YoutubeLogo",
]
var moduleBaseUrl = "https://framer.com/m/phosphor-icons/"
var weightOptions = ["thin", "light", "regular", "bold", "fill", "duotone"]
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
  res[key.toLowerCase()] = key
  return res
}, {})
function Icon3(props) {
  const {
    color,
    selectByList,
    iconSearch,
    iconSelection,
    onClick,
    onMouseDown,
    onMouseUp,
    onMouseEnter,
    onMouseLeave,
    weight,
    mirrored,
  } = props
  const isMounted = useRef(false)
  const iconKey = useIconSelection(
    iconKeys,
    selectByList,
    iconSearch,
    iconSelection,
    lowercaseIconKeyPairs
  )
  const [SelectedIcon, setSelectedIcon] = useState(
    iconKey === "Home" ? House_default(React) : null
  )
  async function importModule() {
    try {
      const version = "0.0.57"
      const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@${version}`
      const module = await import(
        /* webpackIgnore: true */
        /* @vite-ignore */
        iconModuleUrl
      )
      if (isMounted.current) setSelectedIcon(module.default(React))
    } catch (err) {
      if (isMounted.current) setSelectedIcon(null)
    }
  }
  useEffect(() => {
    isMounted.current = true
    importModule()
    return () => {
      isMounted.current = false
    }
  }, [iconKey])
  const isOnCanvas = RenderTarget.current() === RenderTarget.canvas
  const emptyState = isOnCanvas ? <NullState /> : null
  return (
    <motion.div
      style={{
        display: "contents",
      }}
      onClick={onClick}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onMouseDown={onMouseDown}
      onMouseUp={onMouseUp}
    >
      {SelectedIcon ? (
        <svg
          xmlns={"http://www.w3.org/2000/svg"}
          viewBox={"0 0 256 256"}
          style={{
            userSelect: "none",
            width: "100%",
            height: "100%",
            display: "inline-block",
            fill: color,
            color,
            flexShrink: 0,
            transform: mirrored ? "scale(-1, 1)" : void 0,
          }}
          focusable={"false"}
          color={color}
        >
          <SelectedIcon color={color} weight={weight} />
        </svg>
      ) : (
        emptyState
      )}
    </motion.div>
  )
}
Icon3.displayName = "Phosphor"
Icon3.defaultProps = {
  width: 24,
  height: 24,
  iconSelection: "House",
  iconSearch: "House",
  color: "#66F",
  selectByList: true,
  weight: "regular",
  mirrored: false,
}
addPropertyControls(Icon3, {
  selectByList: {
    type: ControlType.Boolean,
    title: "Select",
    enabledTitle: "List",
    disabledTitle: "Search",
    defaultValue: Icon3.defaultProps.selectByList,
  },
  iconSelection: {
    type: ControlType.Enum,
    options: iconKeys,
    defaultValue: Icon3.defaultProps.iconSelection,
    title: "Name",
    hidden: ({ selectByList }) => !selectByList,
    description:
      "Find every icon name on the [Phosphor site](https://phosphoricons.com/)",
  },
  iconSearch: {
    type: ControlType.String,
    title: "Name",
    placeholder: "Menu, Wifi, Box\u2026",
    hidden: ({ selectByList }) => selectByList,
  },
  color: {
    type: ControlType.Color,
    title: "Color",
    defaultValue: Icon3.defaultProps.color,
  },
  weight: {
    type: ControlType.Enum,
    title: "Weight",
    optionTitles: weightOptions.map(
      (piece) => piece.charAt(0).toUpperCase() + piece.slice(1)
    ),
    options: weightOptions,
    defaultValue: Icon3.defaultProps.weight,
  },
  mirrored: {
    type: ControlType.Boolean,
    enabledTitle: "Yes",
    disabledTitle: "No",
    defaultValue: Icon3.defaultProps.mirrored,
  },
  ...defaultEvents,
})

// /:https://framerusercontent.com/modules/rQAyZW1LF2z2C0hJOyNM/5gomtQ1CIfUmbhMUAJt7/NEZBs7an1.js
var PhosphorFonts = getFonts(Icon)
var Phosphor1Fonts = getFonts(Icon3)
var enabledGestures = {
  pboScBVWw: {
    hover: true,
  },
  pEi_b4EV1: {
    hover: true,
  },
}
var cycleOrder = ["pEi_b4EV1", "d8KzG0Glt", "pboScBVWw", "mhXewl9do"]
var serializationHash = "framer-6LRan"
var variantClassNames = {
  d8KzG0Glt: "framer-v-1nlqghi",
  mhXewl9do: "framer-v-utqchl",
  pboScBVWw: "framer-v-iuoe8h",
  pEi_b4EV1: "framer-v-g9dh9n",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.39,
  type: "spring",
}
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`
var Transition = ({ value, children }) => {
  const config = React2.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React2.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var humanReadableVariantMap = {
  Desktop: "pEi_b4EV1",
  New: "pboScBVWw",
  Off: "mhXewl9do",
  Phone: "d8KzG0Glt",
}
var Variants = motion2.create(React2.Fragment)
var getProps = ({ height, id, link, price, width, ...props }) => {
  return {
    ...props,
    LaRWZ1Hqy: link ?? props.LaRWZ1Hqy,
    MSLk_tJaN: price ?? props.MSLk_tJaN ?? "$129",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "pEi_b4EV1",
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
  const fallbackRef = useRef2(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React2.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className,
    layoutId,
    variant,
    MSLk_tJaN: MSLk_tJaN2,
    LaRWZ1Hqy: LaRWZ1Hqy2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "pEi_b4EV1",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const onTap1k9amyg = activeVariantCallback(async (...args) => {
    setVariant("mhXewl9do")
  })
  const sharedStyleClassNames = []
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  const isDisplayed = () => {
    if (gestureVariant === "pboScBVWw-hover") return false
    if (["pboScBVWw", "mhXewl9do"].includes(baseVariant)) return false
    return true
  }
  const isDisplayed1 = () => {
    if (gestureVariant === "pboScBVWw-hover") return true
    if (baseVariant === "pboScBVWw") return true
    return false
  }
  const isDisplayed2 = () => {
    if (gestureVariant === "pboScBVWw-hover") return true
    return false
  }
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <Link
            href={LaRWZ1Hqy2}
            motionChild={true}
            nodeId={"pEi_b4EV1"}
            openInNewTab={true}
            scopeId={"NEZBs7an1"}
            smoothScroll={true}
            {...addPropertyOverrides(
              {
                "pboScBVWw-hover": {
                  href: void 0,
                },
                d8KzG0Glt: {
                  href: void 0,
                },
                mhXewl9do: {
                  href: void 0,
                },
                pboScBVWw: {
                  href: void 0,
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            <motion2.a
              {...restProps}
              {...gestureHandlers}
              className={`${cx(scopingClassNames, "framer-g9dh9n", className, classNames)} framer-1fjbnnd`}
              data-framer-name={"Desktop"}
              layoutDependency={layoutDependency}
              layoutId={"pEi_b4EV1"}
              ref={refBinding}
              style={{
                backgroundColor:
                  "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                borderBottomLeftRadius: 10,
                borderBottomRightRadius: 10,
                borderTopLeftRadius: 10,
                borderTopRightRadius: 10,
                opacity: 1,
                ...style,
              }}
              variants={{
                "pboScBVWw-hover": {
                  opacity: 1,
                },
                "pEi_b4EV1-hover": {
                  opacity: 1,
                },
                mhXewl9do: {
                  opacity: 0,
                },
              }}
              {...addPropertyOverrides(
                {
                  "pboScBVWw-hover": {
                    "data-framer-name": void 0,
                  },
                  "pEi_b4EV1-hover": {
                    "data-framer-name": void 0,
                  },
                  d8KzG0Glt: {
                    "data-framer-name": "Phone",
                  },
                  mhXewl9do: {
                    "data-framer-name": "Off",
                  },
                  pboScBVWw: {
                    "data-framer-name": "New",
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              {isDisplayed() && (
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-idkh3w"}
                  fonts={["GF;Manrope-600"]}
                  layoutDependency={layoutDependency}
                  layoutId={"nwJoRzcD_"}
                  style={{
                    "--extracted-r6o4lv":
                      "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))",
                    "--framer-paragraph-spacing": "0px",
                  }}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      "pEi_b4EV1-hover": {
                        children: (
                          <React2.Fragment>
                            <motion2.p
                              style={{
                                "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                                "--framer-font-family":
                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                "--framer-font-size": "15px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "170%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                              }}
                            >
                              {"Get Template"}
                            </motion2.p>
                          </React2.Fragment>
                        ),
                        fonts: ["GF;Manrope-700"],
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React2.Fragment>
                    <motion2.p
                      style={{
                        "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                        "--framer-font-family":
                          '"Manrope", "Manrope Placeholder", sans-serif',
                        "--framer-font-size": "15px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.04em",
                        "--framer-line-height": "170%",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                      }}
                    >
                      {"Get Template"}
                    </motion2.p>
                  </React2.Fragment>
                </RichText>
              )}
              {isDisplayed() && (
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-a3xg4k"}
                  fonts={["GF;Manrope-600"]}
                  layoutDependency={layoutDependency}
                  layoutId={"VHfKFvQOv"}
                  style={{
                    "--extracted-r6o4lv":
                      "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))",
                    "--framer-paragraph-spacing": "0px",
                    opacity: 0.6,
                  }}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      "pEi_b4EV1-hover": {
                        children: (
                          <React2.Fragment>
                            <motion2.p
                              style={{
                                "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                                "--framer-font-family":
                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                "--framer-font-size": "15px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "170%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                              }}
                            >
                              {"for"}
                            </motion2.p>
                          </React2.Fragment>
                        ),
                        fonts: ["GF;Manrope-700"],
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React2.Fragment>
                    <motion2.p
                      style={{
                        "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                        "--framer-font-family":
                          '"Manrope", "Manrope Placeholder", sans-serif',
                        "--framer-font-size": "15px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.04em",
                        "--framer-line-height": "170%",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                      }}
                    >
                      {"for"}
                    </motion2.p>
                  </React2.Fragment>
                </RichText>
              )}
              {isDisplayed() && (
                <RichText
                  __fromCanvasComponent={true}
                  className={"framer-csy6ye"}
                  fonts={["GF;Manrope-600"]}
                  layoutDependency={layoutDependency}
                  layoutId={"xMEDQKI_5"}
                  style={{
                    "--extracted-r6o4lv":
                      "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))",
                    "--framer-paragraph-spacing": "0px",
                  }}
                  text={MSLk_tJaN2}
                  verticalAlignment={"top"}
                  withExternalLayout={true}
                  {...addPropertyOverrides(
                    {
                      "pEi_b4EV1-hover": {
                        children: (
                          <React2.Fragment>
                            <motion2.p
                              style={{
                                "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                                "--framer-font-family":
                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                "--framer-font-size": "15px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "170%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                              }}
                            >
                              {"$129"}
                            </motion2.p>
                          </React2.Fragment>
                        ),
                        fonts: ["GF;Manrope-700"],
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  <React2.Fragment>
                    <motion2.p
                      style={{
                        "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                        "--framer-font-family":
                          '"Manrope", "Manrope Placeholder", sans-serif',
                        "--framer-font-size": "15px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.04em",
                        "--framer-line-height": "170%",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                      }}
                    >
                      {"$129"}
                    </motion2.p>
                  </React2.Fragment>
                </RichText>
              )}
              {isDisplayed1() && (
                <Image
                  background={{
                    alt: "",
                    fit: "fill",
                    intrinsicHeight: 600,
                    intrinsicWidth: 800,
                    pixelHeight: 1200,
                    pixelWidth: 1600,
                    src: "https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?width=1600&height=1200",
                    srcSet:
                      "https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?scale-down-to=512&width=1600&height=1200 512w,https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?scale-down-to=1024&width=1600&height=1200 1024w,https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?width=1600&height=1200 1600w",
                  }}
                  className={"framer-g34rqy"}
                  data-framer-name={"Image"}
                  layoutDependency={layoutDependency}
                  layoutId={"tURlc2Cdc"}
                  style={{
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8,
                  }}
                  {...addPropertyOverrides(
                    {
                      pboScBVWw: {
                        background: {
                          alt: "",
                          fit: "fill",
                          intrinsicHeight: 600,
                          intrinsicWidth: 800,
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) +
                              (4 +
                                ((componentViewport?.height || 129.5) -
                                  8 -
                                  128) /
                                  2)
                          ),
                          pixelHeight: 1200,
                          pixelWidth: 1600,
                          sizes: `max(${componentViewport?.width || "100vw"} - 8px, 1px)`,
                          src: "https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?width=1600&height=1200",
                          srcSet:
                            "https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?scale-down-to=512&width=1600&height=1200 512w,https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?scale-down-to=1024&width=1600&height=1200 1024w,https://framerusercontent.com/images/JxcdykwyJpRD7JxJJ4qKxNQaHqE.png?width=1600&height=1200 1600w",
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  )}
                >
                  {isDisplayed2() && (
                    <Link
                      href={
                        "https://www.framer.com/marketplace/templates/riwa/"
                      }
                      motionChild={true}
                      nodeId={"f1AQsppcN"}
                      openInNewTab={true}
                      scopeId={"NEZBs7an1"}
                    >
                      <motion2.a
                        className={"framer-jnku93 framer-1fjbnnd"}
                        data-border={true}
                        layoutDependency={layoutDependency}
                        layoutId={"f1AQsppcN"}
                        style={{
                          "--border-bottom-width": "1px",
                          "--border-color": "rgba(255, 255, 255, 0.2)",
                          "--border-left-width": "1px",
                          "--border-right-width": "1px",
                          "--border-style": "solid",
                          "--border-top-width": "1px",
                          backgroundColor:
                            "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))",
                          borderBottomLeftRadius: 20,
                          borderBottomRightRadius: 20,
                          borderTopLeftRadius: 20,
                          borderTopRightRadius: 20,
                        }}
                        transformTemplate={transformTemplate1}
                      >
                        <RichText
                          __fromCanvasComponent={true}
                          className={"framer-qh5bas"}
                          fonts={["GF;Manrope-600"]}
                          layoutDependency={layoutDependency}
                          layoutId={"hsm2qWSU4"}
                          style={{
                            "--extracted-r6o4lv":
                              "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px",
                          }}
                          verticalAlignment={"top"}
                          withExternalLayout={true}
                        >
                          <React2.Fragment>
                            <motion2.p
                              dir={"auto"}
                              style={{
                                "--font-selector": "R0Y7TWFucm9wZS02MDA=",
                                "--framer-font-family":
                                  '"Manrope", "Manrope Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "600",
                                "--framer-letter-spacing": "-0.04em",
                                "--framer-line-height": "170%",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255)))",
                              }}
                            >
                              {"New Template"}
                            </motion2.p>
                          </React2.Fragment>
                        </RichText>
                        <ComponentViewportProvider>
                          <SmartComponentScopedContainer
                            className={"framer-4e66ld-container"}
                            isAuthoredByUser={true}
                            layoutDependency={layoutDependency}
                            layoutId={"v2wAqso4w-container"}
                            nodeId={"v2wAqso4w"}
                            rendersWithMotion={true}
                            scopeId={"NEZBs7an1"}
                            style={{
                              rotate: 45,
                            }}
                          >
                            <Icon
                              color={
                                "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))"
                              }
                              height={"100%"}
                              iconSearch={"arrow-up-right"}
                              iconSelection={"ArrowCircleDown"}
                              id={"v2wAqso4w"}
                              layoutId={"v2wAqso4w"}
                              mirrored={false}
                              selectByList={false}
                              style={{
                                height: "100%",
                                width: "100%",
                              }}
                              weight={"bold"}
                              width={"100%"}
                            />
                          </SmartComponentScopedContainer>
                        </ComponentViewportProvider>
                      </motion2.a>
                    </Link>
                  )}
                  {isDisplayed2() && (
                    <motion2.div
                      className={"framer-1qpy03p"}
                      layoutDependency={layoutDependency}
                      layoutId={"R7NmZTtLp"}
                      style={{
                        background:
                          "linear-gradient(180deg, rgba(0, 0, 0, 0) 40%, rgb(0, 0, 0) 100%)",
                      }}
                    />
                  )}
                </Image>
              )}
              {isDisplayed1() && (
                <motion2.div
                  className={"framer-yedbgy"}
                  data-framer-name={"Notable Work Container"}
                  data-highlight={true}
                  layoutDependency={layoutDependency}
                  layoutId={"lcoPfcTR9"}
                  onTap={onTap1k9amyg}
                  style={{
                    backdropFilter: "blur(25px)",
                    backgroundColor:
                      "var(--token-a2ff6e51-46f4-43bd-9193-b115ff4b5b03, rgb(255, 255, 255))",
                    borderBottomLeftRadius: 100,
                    borderBottomRightRadius: 100,
                    borderTopLeftRadius: 100,
                    borderTopRightRadius: 100,
                    WebkitBackdropFilter: "blur(25px)",
                  }}
                >
                  <RichText
                    __fromCanvasComponent={true}
                    className={"framer-ud9ta"}
                    data-framer-name={"About me"}
                    fonts={["GF;Manrope-700"]}
                    layoutDependency={layoutDependency}
                    layoutId={"Erl5JZl8g"}
                    style={{
                      "--extracted-1eung3n":
                        "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))",
                      "--framer-paragraph-spacing": "0px",
                    }}
                    transformTemplate={transformTemplate2}
                    verticalAlignment={"top"}
                    withExternalLayout={true}
                    {...addPropertyOverrides(
                      {
                        "pboScBVWw-hover": {
                          transformTemplate: transformTemplate1,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    )}
                  >
                    <React2.Fragment>
                      <motion2.h4
                        dir={"auto"}
                        style={{
                          "--font-selector": "R0Y7TWFucm9wZS03MDA=",
                          "--framer-font-family":
                            '"Manrope", "Manrope Placeholder", sans-serif',
                          "--framer-font-size": "12px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "0.1em",
                          "--framer-line-height": "100%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-1eung3n, var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47)))",
                          "--framer-text-transform": "uppercase",
                        }}
                      >
                        {"new"}
                      </motion2.h4>
                    </React2.Fragment>
                  </RichText>
                  <ComponentViewportProvider>
                    <SmartComponentScopedContainer
                      className={"framer-em2y3x-container"}
                      isAuthoredByUser={true}
                      isModuleExternal={true}
                      layoutDependency={layoutDependency}
                      layoutId={"kIQPv79OV-container"}
                      nodeId={"kIQPv79OV"}
                      rendersWithMotion={true}
                      scopeId={"NEZBs7an1"}
                    >
                      <Icon3
                        color={
                          "var(--token-8303387e-d4c2-4989-af33-54d2c870c7ac, rgb(47, 47, 47))"
                        }
                        height={"100%"}
                        iconSearch={"House"}
                        iconSelection={"X"}
                        id={"kIQPv79OV"}
                        layoutId={"kIQPv79OV"}
                        mirrored={false}
                        selectByList={true}
                        style={{
                          height: "100%",
                          width: "100%",
                        }}
                        weight={"bold"}
                        width={"100%"}
                      />
                    </SmartComponentScopedContainer>
                  </ComponentViewportProvider>
                </motion2.div>
              )}
            </motion2.a>
          </Link>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6LRan.framer-1fjbnnd, .framer-6LRan .framer-1fjbnnd { display: block; }",
  ".framer-6LRan.framer-g9dh9n { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: hidden; padding: 10px 12px 10px 12px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-6LRan .framer-idkh3w, .framer-6LRan .framer-csy6ye, .framer-6LRan .framer-qh5bas { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-6LRan .framer-a3xg4k { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
  ".framer-6LRan .framer-g34rqy { aspect-ratio: 1.3333333333333333 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 150px); overflow: visible; position: relative; width: 1px; }",
  ".framer-6LRan .framer-jnku93 { align-content: center; align-items: center; bottom: 10px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 5px 12px 5px 12px; position: absolute; text-decoration: none; width: min-content; z-index: 1; }",
  ".framer-6LRan .framer-4e66ld-container { flex: none; height: 16px; position: relative; width: 16px; }",
  ".framer-6LRan .framer-1qpy03p { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: visible; position: absolute; top: calc(50.205761316872454% - 100% / 2); width: 100%; }",
  ".framer-6LRan .framer-yedbgy { cursor: pointer; flex: none; gap: 10px; height: 20px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: -4px; top: -8px; width: 44px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
  ".framer-6LRan .framer-ud9ta { flex: none; height: auto; left: 50%; position: absolute; top: 50%; white-space: pre; width: auto; }",
  ".framer-6LRan .framer-em2y3x-container { bottom: -20px; flex: none; height: 20px; left: calc(50.00000000000002% - 16px / 2); position: absolute; width: 16px; }",
  ".framer-6LRan.framer-v-1nlqghi.framer-g9dh9n { cursor: unset; padding: 6px 8px 6px 8px; }",
  ".framer-6LRan.framer-v-iuoe8h.framer-g9dh9n { overflow: visible; padding: 4px; width: 170px; will-change: unset; }",
  ".framer-6LRan.framer-v-iuoe8h .framer-g34rqy { height: var(--framer-aspect-ratio-supported, 122px); }",
  ".framer-6LRan.framer-v-utqchl.framer-g9dh9n { cursor: unset; height: 7px; overflow: visible; padding: 4px; width: 170px; will-change: unset; }",
  ".framer-6LRan.framer-v-g9dh9n.hover.framer-g9dh9n { padding: 12px 14px 12px 14px; }",
  ".framer-6LRan.framer-v-iuoe8h.hover.framer-g9dh9n { will-change: unset; }",
  ".framer-6LRan.framer-v-iuoe8h.hover .framer-g34rqy { order: 3; overflow: var(--overflow-clip-fallback, clip); will-change: var(--framer-will-change-override, transform); }",
  ".framer-6LRan.framer-v-iuoe8h.hover .framer-yedbgy { order: 4; }",
  ".framer-6LRan.framer-v-iuoe8h.hover .framer-ud9ta { top: -20px; }",
  ".framer-6LRan.framer-v-iuoe8h.hover .framer-em2y3x-container { bottom: 0px; }",
  '.framer-6LRan[data-border="true"]::after, .framer-6LRan [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
]
var FramerNEZBs7an1 = withCSS(Component2, css, "framer-6LRan")
var stdin_default = FramerNEZBs7an1
FramerNEZBs7an1.displayName = "Purchase Button"
FramerNEZBs7an1.defaultProps = {
  height: 45.5,
  width: 170,
}
addPropertyControls2(FramerNEZBs7an1, {
  variant: {
    options: ["pEi_b4EV1", "d8KzG0Glt", "pboScBVWw", "mhXewl9do"],
    optionTitles: ["Desktop", "Phone", "New", "Off"],
    title: "Variant",
    type: ControlType2.Enum,
  },
  MSLk_tJaN: {
    defaultValue: "$129",
    displayTextArea: false,
    title: "Price",
    type: ControlType2.String,
  },
  onMSLk_tJaNChange: {
    changes: "MSLk_tJaN",
    type: ControlType2.ChangeHandler,
  },
  LaRWZ1Hqy: {
    title: "Link",
    type: ControlType2.Link,
  },
})
addFonts(
  FramerNEZBs7an1,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4jE-_A87jxeN7B.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Manrope",
          source: "google",
          style: "normal",
          uiFamilyName: "Manrope",
          url: "https://fonts.gstatic.com/s/manrope/v20/xn7_YHE41ni1AdIRqAuZuw1Bx9mbZk4aE-_A87jxeN7B.woff2",
          weight: "700",
        },
      ],
    },
    ...PhosphorFonts,
    ...Phosphor1Fonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:purchase-button
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PurchaseButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var purchase_button_default = ComponentWithRoot
export { purchase_button_default as default }
