// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Home' | 'Mobile Home' // Variant
 * tap?: Function // Tap
 * click?: Function // Click
}} Props

 */
import { Grain } from "./chunks/chunk-J6FBOBB4.js"
import { stdin_default } from "./chunks/chunk-FVFRZDEY.js"
import "./chunks/chunk-GLVBB4KT.js"
import "./chunks/chunk-X4FI3VAJ.js"
import "./chunks/chunk-BSDYCGQU.js"
import "./chunks/chunk-6DEZJH2M.js"
import "./chunks/chunk-AYNFMHOT.js"
import "./chunks/chunk-UIGTOHDR.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:sidebar
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/1gZsDgBRmi2xHluYzjaa/rc9ydwjJRfLV6DyAn19S/Mx6ItbCLt.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"
var GrainFonts = getFonts(Grain)
var SidebarcontentFonts = getFonts(stdin_default)
var cycleOrder = ["tQRI9vP_i", "bGetr0QdO"]
var serializationHash = "framer-lNSMz"
var variantClassNames = {
  bGetr0QdO: "framer-v-1eh2kpy",
  tQRI9vP_i: "framer-v-b9fpzs",
}
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {}
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  )
  return nextOverrides
}
var transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var humanReadableVariantMap = {
  "Mobile Home": "bGetr0QdO",
  Home: "tQRI9vP_i",
}
var Variants = motion.create(React.Fragment)
var getProps = ({ click, height, id, tap, width, ...props }) => {
  return {
    ...props,
    sWWyReCNs: click ?? props.sWWyReCNs,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "tQRI9vP_i",
    ZtbBS6tNf: tap ?? props.ZtbBS6tNf,
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className,
    layoutId,
    variant,
    ZtbBS6tNf: ZtbBS6tNf2,
    sWWyReCNs: sWWyReCNs2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "tQRI9vP_i",
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)
  const jBm2sl0Yt4e9g4p = activeVariantCallback(async (...args) => {
    if (ZtbBS6tNf2) {
      const res = await ZtbBS6tNf2(...args)
      if (res === false) return false
    }
  })
  const wWAa9RuML1dewrbl = activeVariantCallback(async (...args) => {
    if (sWWyReCNs2) {
      const res = await sWWyReCNs2(...args)
      if (res === false) return false
    }
  })
  const fB41FrQt51dewrbl = activeVariantCallback(async (...args) => {
    if (sWWyReCNs2) {
      const res = await sWWyReCNs2(...args)
      if (res === false) return false
    }
  })
  const B1I1JHM0Y1dewrbl = activeVariantCallback(async (...args) => {
    if (sWWyReCNs2) {
      const res = await sWWyReCNs2(...args)
      if (res === false) return false
    }
  })
  const IG4QmRo7P1dewrbl = activeVariantCallback(async (...args) => {
    if (sWWyReCNs2) {
      const res = await sWWyReCNs2(...args)
      if (res === false) return false
    }
  })
  const sharedStyleClassNames = []
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition
          value={transition1}
          {...addPropertyOverrides(
            {
              bGetr0QdO: {
                value: void 0,
              },
            },
            baseVariant,
            gestureVariant
          )}
        >
          <motion.nav
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-b9fpzs",
              className,
              classNames
            )}
            data-framer-name={"Home"}
            layoutDependency={layoutDependency}
            layoutId={"tQRI9vP_i"}
            ref={refBinding}
            style={{
              backgroundColor:
                "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
              ...style,
            }}
            {...addPropertyOverrides(
              {
                bGetr0QdO: {
                  "data-framer-name": "Mobile Home",
                },
              },
              baseVariant,
              gestureVariant
            )}
          >
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={"framer-16tfenu-container"}
                isAuthoredByUser={true}
                isModuleExternal={true}
                layoutDependency={layoutDependency}
                layoutId={"NRlBEJWea-container"}
                nodeId={"NRlBEJWea"}
                rendersWithMotion={true}
                scopeId={"Mx6ItbCLt"}
                style={{
                  opacity: 0.3,
                }}
              >
                <Grain
                  height={"100%"}
                  id={"NRlBEJWea"}
                  layoutId={"NRlBEJWea"}
                  opacity={0.09}
                  style={{
                    height: "100%",
                    width: "100%",
                  }}
                  width={"100%"}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
            <ComponentViewportProvider
              height={
                Math.max(0, ((componentViewport?.height || 800) - 0 - 0) / 1) *
                1
              }
              width={componentViewport?.width || "100vw"}
              y={(componentViewport?.y || 0) + 0 + 0}
              {...addPropertyOverrides(
                {
                  bGetr0QdO: {
                    height: 1e3,
                  },
                },
                baseVariant,
                gestureVariant
              )}
            >
              <SmartComponentScopedContainer
                className={"framer-o2vb6c-container"}
                layoutDependency={layoutDependency}
                layoutId={"n5YnSYEid-container"}
                nodeId={"n5YnSYEid"}
                rendersWithMotion={true}
                scopeId={"Mx6ItbCLt"}
              >
                {_jsx(stdin_default, {
                  B1I1JHM0Y: B1I1JHM0Y1dewrbl,
                  fB41FrQt5: fB41FrQt51dewrbl,
                  height: "100%",
                  id: "n5YnSYEid",
                  IG4QmRo7P: IG4QmRo7P1dewrbl,
                  jBm2sl0Yt: jBm2sl0Yt4e9g4p,
                  layoutId: "n5YnSYEid",
                  style: {
                    height: "100%",
                    width: "100%",
                  },
                  width: "100%",
                  wWAa9RuML: wWAa9RuML1dewrbl,
                })}
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion.nav>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-lNSMz.framer-p6o75n, .framer-lNSMz .framer-p6o75n { display: block; }",
  ".framer-lNSMz.framer-b9fpzs { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 800px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 600px; }",
  ".framer-lNSMz .framer-16tfenu-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); pointer-events: none; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: -1; }",
  ".framer-lNSMz .framer-o2vb6c-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; }",
  ".framer-lNSMz.framer-v-1eh2kpy.framer-b9fpzs { height: min-content; width: 390px; }",
  ".framer-lNSMz.framer-v-1eh2kpy .framer-16tfenu-container { height: 109px; top: calc(50.00000000000002% - 109px / 2); }",
  ".framer-lNSMz.framer-v-1eh2kpy .framer-o2vb6c-container { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 1); }",
]
var FramerMx6ItbCLt = withCSS(Component, css, "framer-lNSMz")
var stdin_default2 = FramerMx6ItbCLt
FramerMx6ItbCLt.displayName = "Sidebar"
FramerMx6ItbCLt.defaultProps = {
  height: 800,
  width: 600,
}
addPropertyControls(FramerMx6ItbCLt, {
  variant: {
    options: ["tQRI9vP_i", "bGetr0QdO"],
    optionTitles: ["Home", "Mobile Home"],
    title: "Variant",
    type: ControlType.Enum,
  },
  ZtbBS6tNf: {
    title: "Tap",
    type: ControlType.EventHandler,
  },
  sWWyReCNs: {
    title: "Click",
    type: ControlType.EventHandler,
  },
})
addFonts(
  FramerMx6ItbCLt,
  [
    {
      explicitInter: true,
      fonts: [],
    },
    ...GrainFonts,
    ...SidebarcontentFonts,
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)
FramerMx6ItbCLt.loader = {
  load: (props, context) => {
    const locale = context.locale
    return Promise.allSettled([forwardLoader(stdin_default, {}, context)])
  },
}

// virtual:sidebar
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {
  base: "tQRI9vP_i",
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default2, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SidebarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default2}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default2)
var sidebar_default = ComponentWithRoot
export { sidebar_default as default }
