// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * text?: string // Text
 * fontFamily?: string // Font Family
 * fontSize?: number // Font Size
 * fontWeight?: 'Regular' | 'Medium' | 'Bold' // Font Weight
 * lineHeight?: number // Line Height
 * letterSpacing?: number // Letter Spacing
 * paragraphAlign?: 'Left' | 'Center' | 'Right' // Paragraph Align
 * duration?: number // Duration
 * easing?: 'Ease In Out' | 'Ease In' | 'Ease Out' | 'Linear' // Easing
 * transitionStartIndex?: number // Transition Start Index
}} Props

 */
import { Text_Color_Letters } from "./chunks/chunk-IT3EBHZO.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:text-opacity-letters
import { Fragment } from "react"
import { ContextProviders } from "unframer"
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <Text_Color_Letters {...rest} />
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TextOpacityLettersFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={Text_Color_Letters}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, Text_Color_Letters)
var text_opacity_letters_default = ComponentWithRoot
export { text_opacity_letters_default as default }
