// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project adc980491d2c803a "bibotecture", do not edit manually */
"use client"

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * tickerTitle?: string // Ticker Title
 * tickerImage?: {src: string, srcSet?: string, alt?: string} // Ticker Image
}} Props

 */
import { Ticker, className, css, fonts } from "./chunks/chunk-UIGTOHDR.js"
import { routes } from "./chunks/chunk-NJY7DQ5Z.js"

// virtual:ticker-component
import { Fragment as Fragment2 } from "react"
import { ContextProviders } from "unframer"

// /:https://framerusercontent.com/modules/rRbjdDX4AG2lCuLCo213/LNo5chhwZ2E8cvuiFA8W/prrncmU1P.js
import { jsx as _jsx } from "react/jsx-runtime"
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Image,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "unframer"
import { LayoutGroup, motion, MotionConfigContext } from "unframer"
import * as React from "react"
import { useRef } from "react"
var TickerFonts = getFonts(Ticker)
var serializationHash = "framer-GPm8C"
var variantClassNames = {
  dRyBqe_mX: "framer-v-z2c92k",
}
var transition1 = {
  bounce: 0.2,
  delay: 0,
  duration: 0.4,
  type: "spring",
}
var toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value
  }
  return typeof value === "string"
    ? {
        src: value,
      }
    : void 0
}
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext)
  const transition = value ?? config.transition
  const contextValue = React.useMemo(
    () => ({
      ...config,
      transition,
    }),
    [JSON.stringify(transition)]
  )
  return (
    <MotionConfigContext.Provider value={contextValue}>
      {children}
    </MotionConfigContext.Provider>
  )
}
var Variants = motion.create(React.Fragment)
var getProps = ({ height, id, tickerImage, tickerTitle, width, ...props }) => {
  return {
    ...props,
    HJVq4tdvX: tickerTitle ?? props.HJVq4tdvX ?? "MOJAVE",
    ncmHLBeGW: tickerImage ??
      props.ncmHLBeGW ?? {
        pixelHeight: 788,
        pixelWidth: 1400,
        src: "https://framerusercontent.com/images/cJeztLXJxrBzrjT5araxZh0MA.jpg?width=1400&height=788",
        srcSet:
          "https://framerusercontent.com/images/cJeztLXJxrBzrjT5araxZh0MA.jpg?scale-down-to=512&width=1400&height=788 512w,https://framerusercontent.com/images/cJeztLXJxrBzrjT5araxZh0MA.jpg?scale-down-to=1024&width=1400&height=788 1024w,https://framerusercontent.com/images/cJeztLXJxrBzrjT5araxZh0MA.jpg?width=1400&height=788 1400w",
      },
  }
}
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency
  return variants.join("-")
}
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null)
  const refBinding = ref ?? fallbackRef
  const defaultLayoutId = React.useId()
  const { activeLocale, setLocale } = useLocaleInfo()
  const componentViewport = useComponentViewport()
  const {
    style,
    className: className2,
    layoutId,
    variant,
    HJVq4tdvX: HJVq4tdvX2,
    ncmHLBeGW: ncmHLBeGW2,
    ...restProps
  } = getProps(props)
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "dRyBqe_mX",
    ref: refBinding,
    variant,
    variantClassNames,
  })
  const layoutDependency = createLayoutDependency(props, variants)
  const sharedStyleClassNames = [className]
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)
  return (
    <LayoutGroup id={layoutId ?? defaultLayoutId}>
      <Variants animate={variants} initial={false}>
        <Transition value={transition1}>
          <motion.div
            {...restProps}
            {...gestureHandlers}
            className={cx(
              scopingClassNames,
              "framer-z2c92k",
              className2,
              classNames
            )}
            data-framer-name={"Default"}
            layoutDependency={layoutDependency}
            layoutId={"dRyBqe_mX"}
            ref={refBinding}
            style={{
              ...style,
            }}
          >
            <ComponentViewportProvider>
              <SmartComponentScopedContainer
                className={"framer-1pzuu04-container"}
                isAuthoredByUser={true}
                isModuleExternal={true}
                layoutDependency={layoutDependency}
                layoutId={"SU18rcLyf-container"}
                nodeId={"SU18rcLyf"}
                rendersWithMotion={true}
                scopeId={"prrncmU1P"}
              >
                <Ticker
                  alignment={"center"}
                  direction={"left"}
                  fadeOptions={{
                    fadeAlpha: 0,
                    fadeContent: false,
                    fadeInset: 0,
                    fadeWidth: 0,
                    overflow: true,
                  }}
                  gap={46}
                  height={"100%"}
                  hoverFactor={1}
                  id={"SU18rcLyf"}
                  layoutId={"SU18rcLyf"}
                  padding={10}
                  paddingBottom={10}
                  paddingLeft={10}
                  paddingPerSide={false}
                  paddingRight={10}
                  paddingTop={10}
                  sizingOptions={{
                    heightType: true,
                    widthType: true,
                  }}
                  slots={[
                    <motion.div
                      className={"framer-1hoy1d"}
                      data-framer-name={"Text"}
                      layoutDependency={layoutDependency}
                      layoutId={"M8txWY8me"}
                    >
                      <RichText
                        __fromCanvasComponent={true}
                        className={"framer-1ryto90"}
                        data-framer-name={"Text"}
                        fonts={["Inter"]}
                        layoutDependency={layoutDependency}
                        layoutId={"Z38KKkNb2"}
                        style={{
                          "--extracted-r6o4lv":
                            "var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12))",
                          "--framer-paragraph-spacing": "0px",
                        }}
                        text={HJVq4tdvX2}
                        verticalAlignment={"top"}
                        withExternalLayout={true}
                      >
                        <React.Fragment>
                          <motion.p
                            className={"framer-styles-preset-bcq4ql"}
                            data-styles-preset={"uDlGteBKM"}
                            style={{
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, var(--token-e5a910e4-bdea-462a-af15-d6d1132b60b2, rgb(10, 10, 12)))",
                            }}
                          >
                            {"MOJAVE"}
                          </motion.p>
                        </React.Fragment>
                      </RichText>
                    </motion.div>,
                    <Image
                      background={{
                        alt: "",
                        fit: "fill",
                        pixelHeight: 661,
                        pixelWidth: 880,
                        sizes: "200px",
                        ...toResponsiveImage(ncmHLBeGW2),
                      }}
                      className={"framer-jdsrvk"}
                      data-framer-name={"Image"}
                      layoutDependency={layoutDependency}
                      layoutId={"RldBjFyEU"}
                    />,
                  ]}
                  speed={60}
                  style={{
                    height: "100%",
                    width: "100%",
                  }}
                  width={"100%"}
                />
              </SmartComponentScopedContainer>
            </ComponentViewportProvider>
          </motion.div>
        </Transition>
      </Variants>
    </LayoutGroup>
  )
})
var css2 = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-GPm8C.framer-1jhkyng, .framer-GPm8C .framer-1jhkyng { display: block; }",
  ".framer-GPm8C.framer-z2c92k { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-GPm8C .framer-1pzuu04-container { flex: none; height: 60px; position: relative; width: 1200px; z-index: 1; }",
  ".framer-GPm8C .framer-1hoy1d { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-GPm8C .framer-1ryto90 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-GPm8C .framer-jdsrvk { height: 60px; overflow: hidden; position: relative; width: 200px; will-change: var(--framer-will-change-filter-override, filter); }",
  ...css,
]
var FramerprrncmU1P = withCSS(Component, css2, "framer-GPm8C")
var stdin_default = FramerprrncmU1P
FramerprrncmU1P.displayName = "Ticker Component"
FramerprrncmU1P.defaultProps = {
  height: 60,
  width: 1200,
}
addPropertyControls(FramerprrncmU1P, {
  HJVq4tdvX: {
    defaultValue: "MOJAVE",
    displayTextArea: false,
    title: "Ticker Title",
    type: ControlType.String,
  },
  ncmHLBeGW: {
    __defaultAssetReference:
      "data:framer/asset-reference,cJeztLXJxrBzrjT5araxZh0MA.jpg?originalFilename=Mojave-Day_preview.jpg&preferredSize=auto",
    title: "Ticker Image",
    type: ControlType.ResponsiveImage,
  },
})
addFonts(
  FramerprrncmU1P,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...TickerFonts,
    ...getFontsFromSharedStyle(fonts),
  ],
  {
    supportsExplicitInterCodegen: true,
  }
)

// virtual:ticker-component
import { WithFramerBreakpoints } from "unframer"
import { jsx } from "react/jsx-runtime"
var locales = []
var defaultResponsiveVariants = {}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      {jsx(stdin_default, {
        ...rest,
      })}
    </ContextProviders>
  )
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TickerComponentFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
  return (
    <ContextProviders
      routes={routes}
      framerSiteId={
        "adc980491d2c803a2ec579e951beaca75b0a7ef17e12eb37b3cf1a8f3285813c"
      }
      locale={locale}
      locales={locales}
    >
      <WithFramerBreakpoints
        Component={stdin_default}
        variants={defaultResponsiveVariants}
        {...rest}
      />
    </ContextProviders>
  )
}
Object.assign(ComponentWithRoot, stdin_default)
var ticker_component_default = ComponentWithRoot
export { ticker_component_default as default }
